exports_files([
    "gtest.BUILD",
    "glpk.BUILD",
    "swig.BUILD",
    "scip.BUILD",
    "scip.patch",
    "bliss.BUILD",
    "bliss-0.73.patch",
    #    "zlib.BUILD",
    "archive_helper.bzl",
])
