sed "s/;Cbc::/;Cbc::CoinUtils.lib;Cbc::/" ortools.vcxproj -i
sed "s/;Cbc::/;Cbc::Cbc.lib;Cbc::/" ortools.vcxproj -i
sed "s/;Cbc::/;Cbc::Clp.lib;Cbc::/" ortools.vcxproj -i
sed "s/;Cbc::/;Cbc::Osi.lib;Cbc::/" ortools.vcxproj -i
sed "s/;Cbc::/;Cbc::Cgl.lib;Cbc::/" ortools.vcxproj -i
sed "s/;Cbc::OsiCbc\.lib;/;Cbc::OsiClp.lib;/g" ortools.vcxproj -i
sed "s/;Cbc::ClpSolver\.lib;/;Cbc::CbcSolver.lib;/g" ortools.vcxproj -i
sed "s/;Cbc::/;..\/dependencies\/install\/lib\/coin\/lib/g" ortools.vcxproj -i
sed "s/\.dll/.lib/g" ortools.vcxproj -i
sed "s/DynamicLibrary/StaticLibrary/g" ortools.vcxproj -i

sed "s/;Cbc::/;Cbc::CoinUtils.lib;Cbc::/" examples/cpp/*.vcxproj -i
sed "s/;Cbc::/;Cbc::Cbc.lib;Cbc::/" examples/cpp/*.vcxproj -i
sed "s/;Cbc::/;Cbc::Clp.lib;Cbc::/" examples/cpp/*.vcxproj -i
sed "s/;Cbc::/;Cbc::Osi.lib;Cbc::/" examples/cpp/*.vcxproj -i
sed "s/;Cbc::/;Cbc::Cgl.lib;Cbc::/" examples/cpp/*.vcxproj -i
sed "s/;Cbc::OsiCbc\.lib;/;Cbc::OsiClp.lib;/g" examples/cpp/*.vcxproj -i
sed "s/;Cbc::ClpSolver\.lib;/;Cbc::CbcSolver.lib;/g" examples/cpp/*.vcxproj -i
sed "s/;Cbc::/;..\/..\/..\/dependencies\/install\/lib\/coin\/lib/g" examples/cpp/*.vcxproj -i
