# Please copy this file to Makefile.local and edit to accomodate your needs.

# Python version (to be used to find include files).
UNIX_PYTHON_VER=2.6
# Where gflags is installed.
UNIX_GFLAGS_DIR=../gflags-1.4
# Swig binary.
UNIX_SWIG_BINARY=swig
# Where protocol buffers are installed
UNIX_PROTOBUF_DIR=../protobuf-2.3.0
# This is the root directory of the CLP installation. Please undefine if CLP is
# not installed. If you have installed CBC, CLP_DIR can have the same value as
# CBC_DIR.
UNIX_CLP_DIR=../cbc-2.6.2
# This is the root directory of the CBC installation. Please undefine if CBC is
# not installed.
UNIX_CBC_DIR=../cbc-2.6.2
# This is the root directory of glpk installation. Please undefine if GLPK is
# not installed.
UNIX_GLPK_DIR=../glpk-4.45
# Linux jdk root
# first, determine 32 or 64 bits.
ifeq "$(SYSTEM)" "unix"
  LBITS := $(shell getconf LONG_BIT)
  ifeq ($(LBITS),64)
     JDK_EXT=64
  else
    JDK_EXT=32
  endif
endif

LINUX_JDK_ROOT=/usr/local/buildtools/java/jdk-$(JDK_EXT)
# Include files path for java on mac os X
MAC_JDK_HEADERS=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/include
#MAC_JDK_HEADERS=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bundle/Headers

# Please edit the following:
WINDOWS_GFLAGS_DIR=..\\gflags-1.4
WINDOWS_ZLIB_DIR=..\\zlib-1.2.5
WINDOWS_ZLIB_NAME=zlib.lib
WINDOWS_SWIG_BINARY=..\\swigwin-2.0.0\\swig.exe
WINDOWS_PROTOBUF_DIR=..\\protobuf-2.3.0
WINDOWS_PYTHON_DIR=c:\\Python27
WINDOWS_PYTHON_LIB=c:\\Python27\\libs\\python27.lib
# This is the root directory of the CLP installation. Please undefine if CLP is
# not installed. If you have installed CBC, CLP_DIR can have the same value as
# CBC_DIR.
WINDOWS_CLP_DIR=..\\cbc-2.6.2
WINDOWS_CLP_PACKAGE=Clp 1.13.2
# This is the root directory of the CBC installation. Please undefine if CBC is
# not installed.
WINDOWS_CBC_DIR=..\\cbc-2.6.2
WINDOWS_CBC_PACKAGE=Cbc 2.6.2
# This is the root directory of glpk installation. Please undefine if GLPK is
# not installed.
WINDOWS_GLPK_DIR=..\\glpk-4.45


# This describes the python installation windows.
WINDOWS_PYTHON_INC=/Ic:\\Python27\\include
WINDOWS_PYTHON_LNK=c:\\Python27\\libs\\python27.lib

# This descrives the java installation on windows.
WINDOWS_JDK_DIR=c:\Program Files\Java\jdk1.6.0_24
