g++ -shared -fPIC \
	 -o lib/libortools.so \
	  objs/base/bitmap.o objs/base/callback.o objs/base/file.o objs/base/join.o objs/base/mutex.o objs/base/notification.o objs/base/numbers.o objs/base/random.o objs/base/recordio.o objs/base/split.o objs/base/string_view.o objs/base/stringprintf.o objs/base/sysinfo.o objs/base/threadpool.o objs/base/time_support.o objs/base/timer.o \
	   objs/port/file_nonport.o objs/port/sysinfo_nonport.o \
	    objs/util/bitset.o objs/util/cached_log.o objs/util/file_util.o objs/util/fp_utils.o objs/util/graph_export.o objs/util/piecewise_linear_function.o objs/util/proto_tools.o objs/util/range_query_function.o objs/util/rational_approximation.o objs/util/sigint.o objs/util/sorted_interval_list.o objs/util/stats.o objs/util/time_limit.o objs/util/xml_helper.o objs/util/optional_boolean.pb.o \
	     objs/data/jobshop_scheduling_parser.o objs/data/rcpsp_parser.o objs/data/set_covering_data.o objs/data/set_covering_parser.o objs/data/jobshop_scheduling.pb.o objs/data/rcpsp.pb.o \
	      objs/lp_data/lp_data.o objs/lp_data/lp_data_utils.o objs/lp_data/lp_decomposer.o objs/lp_data/lp_print_utils.o objs/lp_data/lp_types.o objs/lp_data/lp_utils.o objs/lp_data/matrix_scaler.o objs/lp_data/matrix_utils.o objs/lp_data/model_reader.o objs/lp_data/mps_reader.o objs/lp_data/proto_utils.o objs/lp_data/sparse.o objs/lp_data/sparse_column.o \
	       objs/glop/basis_representation.o objs/glop/dual_edge_norms.o objs/glop/entering_variable.o objs/glop/initial_basis.o objs/glop/lp_solver.o objs/glop/lu_factorization.o objs/glop/markowitz.o objs/glop/preprocessor.o objs/glop/primal_edge_norms.o objs/glop/reduced_costs.o objs/glop/revised_simplex.o objs/glop/status.o objs/glop/update_row.o objs/glop/variable_values.o objs/glop/variables_info.o objs/glop/parameters.pb.o \
	        objs/graph/assignment.o objs/graph/astar.o objs/graph/bellman_ford.o objs/graph/cliques.o objs/graph/connected_components.o objs/graph/dijkstra.o objs/graph/linear_assignment.o objs/graph/max_flow.o objs/graph/min_cost_flow.o objs/graph/shortestpaths.o objs/graph/util.o objs/graph/flow_problem.pb.o \
		 objs/algorithms/dynamic_partition.o objs/algorithms/dynamic_permutation.o objs/algorithms/find_graph_symmetries.o objs/algorithms/hungarian.o objs/algorithms/knapsack_solver.o objs/algorithms/sparse_permutation.o \
		  objs/sat/all_different.o objs/sat/boolean_problem.o objs/sat/circuit.o objs/sat/clause.o objs/sat/cp_constraints.o objs/sat/cp_model.o objs/sat/cp_model_checker.o objs/sat/cp_model_expand.o objs/sat/cp_model_lns.o objs/sat/cp_model_loader.o objs/sat/cp_model_objective.o objs/sat/cp_model_presolve.o objs/sat/cp_model_search.o objs/sat/cp_model_solver.o objs/sat/cp_model_symmetries.o objs/sat/cp_model_utils.o objs/sat/cumulative.o objs/sat/disjunctive.o objs/sat/drat_checker.o objs/sat/drat_proof_handler.o objs/sat/drat_writer.o objs/sat/encoding.o objs/sat/integer.o objs/sat/integer_expr.o objs/sat/integer_search.o objs/sat/intervals.o objs/sat/linear_programming_constraint.o objs/sat/linear_relaxation.o objs/sat/lp_utils.o objs/sat/optimization.o objs/sat/overload_checker.o objs/sat/pb_constraint.o objs/sat/precedences.o objs/sat/probing.o objs/sat/restart.o objs/sat/sat_decision.o objs/sat/sat_solver.o objs/sat/simplification.o objs/sat/symmetry.o objs/sat/table.o objs/sat/theta_tree.o objs/sat/timetable.o objs/sat/timetable_edgefinding.o objs/sat/util.o objs/sat/boolean_problem.pb.o objs/sat/cp_model.pb.o objs/sat/sat_parameters.pb.o \
		   objs/bop/bop_base.o objs/bop/bop_fs.o objs/bop/bop_lns.o objs/bop/bop_ls.o objs/bop/bop_portfolio.o objs/bop/bop_solution.o objs/bop/bop_solver.o objs/bop/bop_util.o objs/bop/complete_optimizer.o objs/bop/integral_solver.o objs/bop/bop_parameters.pb.o \
		    objs/linear_solver/bop_interface.o objs/linear_solver/cbc_interface.o objs/linear_solver/clp_interface.o objs/linear_solver/cplex_interface.o objs/linear_solver/glop_interface.o objs/linear_solver/glop_utils.o objs/linear_solver/glpk_interface.o objs/linear_solver/gurobi_interface.o objs/linear_solver/linear_expr.o objs/linear_solver/linear_solver.o objs/linear_solver/model_exporter.o objs/linear_solver/model_validator.o objs/linear_solver/scip_interface.o objs/linear_solver/linear_solver.pb.o \
		     objs/constraint_solver/ac4_mdd_reset_table.o objs/constraint_solver/ac4r_table.o objs/constraint_solver/alldiff_cst.o objs/constraint_solver/assignment.o objs/constraint_solver/collect_variables.o objs/constraint_solver/constraint_solver.o objs/constraint_solver/constraints.o objs/constraint_solver/count_cst.o objs/constraint_solver/default_search.o objs/constraint_solver/demon_profiler.o objs/constraint_solver/deviation.o objs/constraint_solver/diffn.o objs/constraint_solver/element.o objs/constraint_solver/expr_array.o objs/constraint_solver/expr_cst.o objs/constraint_solver/expressions.o objs/constraint_solver/gcc.o objs/constraint_solver/graph_constraints.o objs/constraint_solver/hybrid.o objs/constraint_solver/interval.o objs/constraint_solver/io.o objs/constraint_solver/local_search.o objs/constraint_solver/model_cache.o objs/constraint_solver/nogoods.o objs/constraint_solver/pack.o objs/constraint_solver/range_cst.o objs/constraint_solver/resource.o objs/constraint_solver/routing.o objs/constraint_solver/routing_flags.o objs/constraint_solver/routing_neighborhoods.o objs/constraint_solver/routing_search.o objs/constraint_solver/sat_constraint.o objs/constraint_solver/sched_constraints.o objs/constraint_solver/sched_expr.o objs/constraint_solver/sched_search.o objs/constraint_solver/search.o objs/constraint_solver/softgcc.o objs/constraint_solver/table.o objs/constraint_solver/timetabling.o objs/constraint_solver/trace.o objs/constraint_solver/tree_monitor.o objs/constraint_solver/utilities.o objs/constraint_solver/visitor.o objs/constraint_solver/assignment.pb.o objs/constraint_solver/demon_profiler.pb.o objs/constraint_solver/model.pb.o objs/constraint_solver/routing_enums.pb.o objs/constraint_solver/routing_parameters.pb.o objs/constraint_solver/search_limit.pb.o objs/constraint_solver/solver_parameters.pb.o \
		       /opt/scipoptsuite-5.0.1/scip/lib/static/libscip.linux.x86_64.gnu.opt.a /opt/scipoptsuite-5.0.1/scip/lib/static/libnlpi.cppad.linux.x86_64.gnu.opt.a /opt/scipoptsuite-5.0.1/scip/lib/static/liblpispx2.linux.x86_64.gnu.opt.a /opt/scipoptsuite-5.0.1/scip/lib/static/libsoplex.linux.x86_64.gnu.opt.a /opt/scipoptsuite-5.0.1/scip/lib/static/libtpitny.linux.x86_64.gnu.opt.a -Wl,-rpath /opt/gurobi800/linux64/lib/ -L/opt/gurobi800/linux64/lib/ -m64 -lc -ldl -lm -lpthread -lgurobi80 -L/opt/CPLEX_Studio_Community128/cplex/lib/x86-64_linux/static_pic -lcplex -lm -lpthread -ldl -L/opt/or-tools/dependencies/install/lib -lgflags -L/opt/or-tools/dependencies/install/lib -lglog -L/opt/or-tools/dependencies/install/lib/ -lprotobuf -L/opt/or-tools/dependencies/install/lib -lCbcSolver -lCbc -lOsiCbc -L/opt/or-tools/dependencies/install/lib -lCgl -L/opt/or-tools/dependencies/install/lib -lClpSolver -lClp -lOsiClp -L/opt/or-tools/dependencies/install/lib -lOsi -L/opt/or-tools/dependencies/install/lib -lCoinUtils \
		        -lz -lrt -lpthread -Wl,-rpath,'$ORIGIN' -Wl,-rpath,'$ORIGIN/../lib' -Wl,-rpath,'$ORIGIN/../dependencies/install/lib64' -Wl,-rpath,'$ORIGIN/../dependencies/install/lib'
