from setuptools import setup
import glob
import os

setup(
    name='or-tools',
    version='1.0',
    packages=[
        'src/constraint_solver',
        'src/gen/constraint_solver',
        'src/linear_solver',
        'src/gen/linear_solver',
        'src/graph',
        'src/gen/graph',
        'src/algorithms',
        'src/gen/algorithms',
        ],
    data_files=[('lib', [
                'lib/_pywrapcp.so',
                'lib/_pywraprouting.so',
                'lib/_pywraplp.so',
                'lib/_pywrapknapsack_solver.so',
                'lib/_pywrapgraph.so',
                ]),
                ('or-tools', ['LICENSE-2.0.txt',]),
                (os.path.join('or-tools', 'examples', 'python'),
                 glob.glob(os.path.join('examples', 'python', '*.py'))),
                ('or-tools/data/bacp',
                 glob.glob(os.path.join('data', 'bacp', '*'))),
                ('or-tools/data/cvrptw',
                 glob.glob(os.path.join('data', 'cvrptw', '*'))),
                ('or-tools/data/discrete_tomography',
                 glob.glob(os.path.join('data', 'discrete_tomography', '*'))),
                ('or-tools/data/et_jobshop/jet',
                 glob.glob(os.path.join('data', 'et_jobshop', 'jet', '*'))),
                ('or-tools/data/et_jobshop/dyn',
                 glob.glob(os.path.join('data', 'et_jobshop', 'dyn', '*'))),
                ('or-tools/data/fill_a_pix',
                 glob.glob(os.path.join('data', 'fill_a_pix', '*'))),
                ('or-tools/data/jobshop',
                 glob.glob(os.path.join('data', 'jobshop', '*'))),
                ('or-tools/data/minesweeper',
                 glob.glob(os.path.join('data', 'minesweeper', '*'))),
                ('or-tools/data/multidim_knapsack',
                 glob.glob(os.path.join('data', 'multidim_knapsack', '*'))),
                ('or-tools/data/nonogram_regular',
                 glob.glob(os.path.join('data', 'nonogram_regular', '*'))),
                ('or-tools/data/pdptw',
                 glob.glob(os.path.join('data', 'pdptw', '*'))),
                ('or-tools/data/quasigroup_completion',
                 glob.glob(os.path.join('data', 'quasigroup_completion', '*'))),
                ('or-tools/data/rogo',
                 glob.glob(os.path.join('data', 'rogo', '*'))),
                ('or-tools/data/steel_mill',
                 glob.glob(os.path.join('data', 'steel_mill', '*'))),
                ('or-tools/data/strimko',
                 glob.glob(os.path.join('data', 'strimko', '*'))),
                ('or-tools/data/survo_puzzleX',
                 glob.glob(os.path.join('data', 'survo_puzzle', '*'))),
                ],
    license='Apache 2.0',
    author = "Google Inc",
    author_email = "lperron@google.com",
    description = "Google OR-Tools",
    keywords = "operations research, constraint programming",
    url = "http://code.google.com/p/or-toosl/",
)
