package(default_visibility = ["//visibility:public"])

cc_library(
    name = "init",
    hdrs = ["init.h"],
    deps = [
        "//ortools/base",
        "//ortools/sat:cp_model_solver",
        "@com_google_absl//absl/flags:flag",
    ],
)
