# Copyright 2010-2025 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@contrib_rules_jvm//java:defs.bzl", "java_junit5_test")

package(default_visibility = ["//visibility:public"])

java_junit5_test(
    name = "ModelIdTest",
    srcs = ["ModelIdTest.java"],
    test_class = "com.google.ortools.mathopt.ModelIdTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:model_id",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "SparseContainersTest",
    srcs = ["SparseContainersTest.java"],
    test_class = "com.google.ortools.mathopt.SparseContainersTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:model_element",
        "//ortools/java/com/google/ortools/mathopt:sparse_containers",
        "//ortools/math_opt:sparse_containers_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "VariableTest",
    srcs = ["VariableTest.java"],
    test_class = "com.google.ortools.mathopt.VariableTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:hash_linear_expression",
        "//ortools/java/com/google/ortools/mathopt:model_id",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/math_opt:model_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "VariablesTest",
    srcs = ["VariablesTest.java"],
    test_class = "com.google.ortools.mathopt.VariablesTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:model_id",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt:variables",
        "//ortools/math_opt:model_java_proto",
        "//ortools/math_opt:model_update_java_proto",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "LinearConstraintTest",
    srcs = ["LinearConstraintTest.java"],
    test_class = "com.google.ortools.mathopt.LinearConstraintTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:hash_linear_expression",
        "//ortools/java/com/google/ortools/mathopt:linear_constraint",
        "//ortools/java/com/google/ortools/mathopt:model_id",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt:variables",
        "//ortools/math_opt:model_java_proto",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_jspecify_jspecify",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "IndicatorConstraintTest",
    srcs = ["IndicatorConstraintTest.java"],
    test_class = "com.google.ortools.mathopt.IndicatorConstraintTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:indicator_constraint",
        "//ortools/java/com/google/ortools/mathopt:model_id",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/math_opt:model_java_proto",
        "//ortools/math_opt:sparse_containers_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "IndicatorConstraintsTest",
    srcs = ["IndicatorConstraintsTest.java"],
    test_class = "com.google.ortools.mathopt.IndicatorConstraintsTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:expressions",
        "//ortools/java/com/google/ortools/mathopt:indicator_constraint",
        "//ortools/java/com/google/ortools/mathopt:indicator_constraints",
        "//ortools/java/com/google/ortools/mathopt:model_id",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt:variables",
        "//ortools/math_opt:model_update_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "MergeTest",
    srcs = ["MergeTest.java"],
    test_class = "com.google.ortools.mathopt.MergeTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:merge",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "ObjectiveTest",
    srcs = ["ObjectiveTest.java"],
    test_class = "com.google.ortools.mathopt.ObjectiveTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:expressions",
        "//ortools/java/com/google/ortools/mathopt:model_id",
        "//ortools/java/com/google/ortools/mathopt:objective",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt:variables",
        "//ortools/math_opt:model_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_jspecify_jspecify",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "AuxiliaryObjectiveTest",
    srcs = ["AuxiliaryObjectiveTest.java"],
    test_class = "com.google.ortools.mathopt.AuxiliaryObjectiveTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:auxiliary_objective",
        "//ortools/java/com/google/ortools/mathopt:model_id",
        "//ortools/java/com/google/ortools/mathopt:objective",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt:variables",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "LinearConstraintsTest",
    srcs = ["LinearConstraintsTest.java"],
    test_class = "com.google.ortools.mathopt.LinearConstraintsTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:linear_constraint",
        "//ortools/java/com/google/ortools/mathopt:linear_constraints",
        "//ortools/java/com/google/ortools/mathopt:model_id",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt:variables",
        "//ortools/math_opt:model_java_proto",
        "//ortools/math_opt:sparse_containers_java_proto",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "LinearConstraintsUpdateTest",
    srcs = ["LinearConstraintsUpdateTest.java"],
    test_class = "com.google.ortools.mathopt.LinearConstraintsUpdateTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:linear_constraint",
        "//ortools/java/com/google/ortools/mathopt:linear_constraints",
        "//ortools/java/com/google/ortools/mathopt:model_id",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt:variables",
        "//ortools/math_opt:model_update_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "ModelTest",
    srcs = ["ModelTest.java"],
    test_class = "com.google.ortools.mathopt.ModelTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:auxiliary_objective",
        "//ortools/java/com/google/ortools/mathopt:expressions",
        "//ortools/java/com/google/ortools/mathopt:hash_linear_expression",
        "//ortools/java/com/google/ortools/mathopt:indicator_constraint",
        "//ortools/java/com/google/ortools/mathopt:linear_constraint",
        "//ortools/java/com/google/ortools/mathopt:model",
        "//ortools/java/com/google/ortools/mathopt:objective",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt/testing:math_opt_proto_subject",
        "//ortools/math_opt:model_java_proto",
        "//ortools/math_opt:model_update_java_proto",
        "//ortools/math_opt:sparse_containers_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "JniSolverTest",
    srcs = ["JniSolverTest.java"],
    test_class = "com.google.ortools.mathopt.JniSolverTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt/testing:string_correspondences",
        "//ortools/math_opt:callback_java_proto",
        "//ortools/math_opt:model_java_proto",
        "//ortools/math_opt:model_parameters_java_proto",
        "//ortools/math_opt:parameters_java_proto",
        "//ortools/math_opt:result_java_proto",
        "//ortools/math_opt:solution_java_proto",
        "//ortools/math_opt/core/java:solver_swig",
        "//ortools/math_opt/solvers:cp_sat_solver",
        "//ortools/math_opt/solvers:glop_solver",
        "//ortools/math_opt/solvers:gscip_solver",
        "//ortools/util/java:java_swig_solve_interrupter_swig",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "BasisTest",
    srcs = ["BasisTest.java"],
    test_class = "com.google.ortools.mathopt.BasisTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:basis",
        "//ortools/java/com/google/ortools/mathopt:linear_constraint",
        "//ortools/java/com/google/ortools/mathopt:model",
        "//ortools/java/com/google/ortools/mathopt:solution_status",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt/testing:math_opt_proto_subject",
        "//ortools/math_opt:solution_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "SolutionStatusTest",
    srcs = ["SolutionStatusTest.java"],
    test_class = "com.google.ortools.mathopt.SolutionStatusTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:solution_status",
        "//ortools/math_opt:solution_java_proto",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "SolutionTest",
    srcs = ["SolutionTest.java"],
    test_class = "com.google.ortools.mathopt.SolutionTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:basis",
        "//ortools/java/com/google/ortools/mathopt:linear_constraint",
        "//ortools/java/com/google/ortools/mathopt:model",
        "//ortools/java/com/google/ortools/mathopt:solution",
        "//ortools/java/com/google/ortools/mathopt:solution_status",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/math_opt:solution_java_proto",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "UtilFromProtoTest",
    srcs = ["UtilFromProtoTest.java"],
    test_class = "com.google.ortools.mathopt.UtilFromProtoTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:linear_constraint",
        "//ortools/java/com/google/ortools/mathopt:model",
        "//ortools/java/com/google/ortools/mathopt:util_from_proto",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/math_opt:sparse_containers_java_proto",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "SolveResultTest",
    srcs = ["SolveResultTest.java"],
    test_class = "com.google.ortools.mathopt.SolveResultTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:basis",
        "//ortools/java/com/google/ortools/mathopt:linear_constraint",
        "//ortools/java/com/google/ortools/mathopt:model",
        "//ortools/java/com/google/ortools/mathopt:solve_result",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/math_opt:result_java_proto",
        "//ortools/math_opt:solution_java_proto",
        "//ortools/math_opt/solvers:osqp_java_proto",
        "//ortools/math_opt/solvers/gscip:gscip_java_proto",
        "//ortools/pdlp:solve_log_java_proto",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "ObjectivesTest",
    srcs = ["ObjectivesTest.java"],
    test_class = "com.google.ortools.mathopt.ObjectivesTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:auxiliary_objective",
        "//ortools/java/com/google/ortools/mathopt:model_id",
        "//ortools/java/com/google/ortools/mathopt:objective",
        "//ortools/java/com/google/ortools/mathopt:objectives",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt:variables",
        "//ortools/math_opt:model_java_proto",
        "//ortools/math_opt:model_update_java_proto",
        "//ortools/math_opt:sparse_containers_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "SolverTypeTest",
    srcs = ["SolverTypeTest.java"],
    test_class = "com.google.ortools.mathopt.SolverTypeTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:solver_type",
        "//ortools/math_opt:parameters_java_proto",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "SolveTest",
    srcs = ["SolveTest.java"],
    test_class = "com.google.ortools.mathopt.SolveTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:basis",
        "//ortools/java/com/google/ortools/mathopt:callback_data",
        "//ortools/java/com/google/ortools/mathopt:callback_event",
        "//ortools/java/com/google/ortools/mathopt:callback_registration",
        "//ortools/java/com/google/ortools/mathopt:callback_result",
        "//ortools/java/com/google/ortools/mathopt:expressions",
        "//ortools/java/com/google/ortools/mathopt:model",
        "//ortools/java/com/google/ortools/mathopt:model_solve_parameters",
        "//ortools/java/com/google/ortools/mathopt:solve",
        "//ortools/java/com/google/ortools/mathopt:solve_parameters",
        "//ortools/java/com/google/ortools/mathopt:solve_result",
        "//ortools/java/com/google/ortools/mathopt:solver_type",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt/testing:math_opt_proto_subject",
        "//ortools/java/com/google/ortools/mathopt/testing:string_correspondences",
        "//ortools/java/com/google/ortools/util:solve_interrupter",
        "//ortools/math_opt:callback_java_proto",
        "//ortools/math_opt:model_parameters_java_proto",
        "//ortools/math_opt:parameters_java_proto",
        "//ortools/math_opt/solvers:cp_sat_solver",
        "//ortools/math_opt/solvers:glop_solver",
        "//ortools/math_opt/solvers:gscip_solver",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "SolveParametersTest",
    srcs = ["SolveParametersTest.java"],
    test_class = "com.google.ortools.mathopt.SolveParametersTest",
    deps = [
        "//ortools/glop:parameters_java_proto",
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:solve_parameters",
        "//ortools/math_opt:parameters_java_proto",
        "//ortools/math_opt/solvers:glpk_java_proto",
        "//ortools/math_opt/solvers:gurobi_java_proto",
        "//ortools/math_opt/solvers:highs_java_proto",
        "//ortools/math_opt/solvers:osqp_java_proto",
        "//ortools/math_opt/solvers:xpress_java_proto",
        "//ortools/math_opt/solvers/gscip:gscip_java_proto",
        "//ortools/pdlp:solvers_java_proto",
        "//ortools/sat:sat_parameters_java_proto",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "ScopedCppMessageCallbackTest",
    srcs = ["ScopedCppMessageCallbackTest.java"],
    test_class = "com.google.ortools.mathopt.ScopedCppMessageCallbackTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:scoped_cpp_message_callback",
        "//ortools/java/com/google/ortools/mathopt/testing:string_correspondences",
        "//ortools/math_opt:callback_java_proto",
        "//ortools/math_opt:model_java_proto",
        "//ortools/math_opt:model_parameters_java_proto",
        "//ortools/math_opt:parameters_java_proto",
        "//ortools/math_opt:result_java_proto",
        "//ortools/math_opt/core/java:solver_swig",  # buildcleaner: keep
        "//ortools/math_opt/solvers:glop_solver",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "CallbackEventTest",
    srcs = ["CallbackEventTest.java"],
    test_class = "com.google.ortools.mathopt.CallbackEventTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:callback_event",
        "//ortools/math_opt:callback_java_proto",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "CallbackResultTest",
    srcs = ["CallbackResultTest.java"],
    test_class = "com.google.ortools.mathopt.CallbackResultTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:callback_result",
        "//ortools/java/com/google/ortools/mathopt:expressions",
        "//ortools/java/com/google/ortools/mathopt:model",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/math_opt:callback_java_proto",
        "//ortools/math_opt:sparse_containers_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "CallbackDataTest",
    srcs = ["CallbackDataTest.java"],
    test_class = "com.google.ortools.mathopt.CallbackDataTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:callback_data",
        "//ortools/java/com/google/ortools/mathopt:callback_event",
        "//ortools/java/com/google/ortools/mathopt:model",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/util:proto_duration_conversion",
        "//ortools/math_opt:callback_java_proto",
        "//ortools/math_opt:sparse_containers_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "CallbackRegistrationTest",
    srcs = ["CallbackRegistrationTest.java"],
    test_class = "com.google.ortools.mathopt.CallbackRegistrationTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:callback_event",
        "//ortools/java/com/google/ortools/mathopt:callback_registration",
        "//ortools/math_opt:callback_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_extensions_truth_proto_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "HashLinearExpressionTest",
    srcs = ["HashLinearExpressionTest.java"],
    test_class = "com.google.ortools.mathopt.HashLinearExpressionTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:hash_linear_expression",
        "//ortools/java/com/google/ortools/mathopt:model",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "LinearConstraintsAddConstraintOverloadTest",
    srcs = ["LinearConstraintsAddConstraintOverloadTest.java"],
    test_class = "com.google.ortools.mathopt.LinearConstraintsAddConstraintOverloadTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:expressions",
        "//ortools/java/com/google/ortools/mathopt:hash_linear_expression",
        "//ortools/java/com/google/ortools/mathopt:linear_constraint",
        "//ortools/java/com/google/ortools/mathopt:linear_constraints",
        "//ortools/java/com/google/ortools/mathopt:model_id",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt:variables",
        "//ortools/java/com/google/ortools/mathopt/testing:linear_constraint_subject",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "ModelAddLinearConstraintOverloadsTest",
    srcs = ["ModelAddLinearConstraintOverloadsTest.java"],
    test_class = "com.google.ortools.mathopt.ModelAddLinearConstraintOverloadsTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:expressions",
        "//ortools/java/com/google/ortools/mathopt:hash_linear_expression",
        "//ortools/java/com/google/ortools/mathopt:linear_constraint",
        "//ortools/java/com/google/ortools/mathopt:model",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt/testing:linear_constraint_subject",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "ExpressionsTest",
    srcs = ["ExpressionsTest.java"],
    test_class = "com.google.ortools.mathopt.ExpressionsTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:expressions",
        "//ortools/java/com/google/ortools/mathopt:hash_linear_expression",
        "//ortools/java/com/google/ortools/mathopt:model",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "ScopedCppSolveCallbackTest",
    srcs = ["ScopedCppSolveCallbackTest.java"],
    test_class = "com.google.ortools.mathopt.ScopedCppSolveCallbackTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:scoped_cpp_solve_callback",
        "//ortools/math_opt:callback_java_proto",
        "//ortools/math_opt:model_java_proto",
        "//ortools/math_opt:model_parameters_java_proto",
        "//ortools/math_opt:parameters_java_proto",
        "//ortools/math_opt:result_java_proto",
        "//ortools/math_opt/core/java:solver_swig",  # buildcleaner: keep
        "//ortools/math_opt/solvers:cp_sat_solver",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "ModelSolveParametersTest",
    srcs = ["ModelSolveParametersTest.java"],
    test_class = "com.google.ortools.mathopt.ModelSolveParametersTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:basis",
        "//ortools/java/com/google/ortools/mathopt:linear_constraint",
        "//ortools/java/com/google/ortools/mathopt:model",
        "//ortools/java/com/google/ortools/mathopt:model_solve_parameters",
        "//ortools/java/com/google/ortools/mathopt:variable",
        "//ortools/java/com/google/ortools/mathopt/testing:math_opt_proto_subject",
        "//ortools/math_opt:model_parameters_java_proto",
        "//ortools/math_opt:solution_java_proto",
        "//ortools/math_opt:sparse_containers_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "MathOptInternalExceptionTest",
    srcs = ["MathOptInternalExceptionTest.java"],
    test_class = "com.google.ortools.mathopt.MathOptInternalExceptionTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:math_opt_internal_exception",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)

java_junit5_test(
    name = "ErrorsTest",
    size = "small",
    srcs = ["ErrorsTest.java"],
    test_class = "com.google.ortools.mathopt.ErrorsTest",
    deps = [
        "//ortools/java/com/google/ortools:Loader",
        "//ortools/java/com/google/ortools/mathopt:errors",
        "//ortools/java/com/google/ortools/mathopt:math_opt_internal_exception",
        "//ortools/util:status_java_proto",
        "@maven//:com_google_truth_truth",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
    ],
)
