# Autogenerated using ProtoBuf.jl v1.3.0
# original file: ortools/sat/lrat.proto (proto2 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export LratImportedClause, LratDeletedClauses, var"LratInferredClause.RatInfo"
export LratExportedClause, LratInferredClause, LratProofStep


struct LratImportedClause
    clause_id::Int64
    literals::Vector{Int32}
end
PB.default_values(::Type{LratImportedClause}) = (;clause_id = zero(Int64), literals = Vector{Int32}())
PB.field_numbers(::Type{LratImportedClause}) = (;clause_id = 1, literals = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:LratImportedClause}, _endpos::Int=0, _group::Bool=false)
    clause_id = zero(Int64)
    literals = PB.BufferedVector{Int32}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            clause_id = PB.decode(d, Int64)
        elseif field_number == 2
            PB.decode!(d, wire_type, literals)
        else
            Base.skip(d, wire_type)
        end
    end
    return LratImportedClause(clause_id, literals[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::LratImportedClause)
    initpos = position(e.io)
    x.clause_id != zero(Int64) && PB.encode(e, 1, x.clause_id)
    !isempty(x.literals) && PB.encode(e, 2, x.literals)
    return position(e.io) - initpos
end
function PB._encoded_size(x::LratImportedClause)
    encoded_size = 0
    x.clause_id != zero(Int64) && (encoded_size += PB._encoded_size(x.clause_id, 1))
    !isempty(x.literals) && (encoded_size += PB._encoded_size(x.literals, 2))
    return encoded_size
end

struct LratDeletedClauses
    clause_ids::Vector{Int64}
end
PB.default_values(::Type{LratDeletedClauses}) = (;clause_ids = Vector{Int64}())
PB.field_numbers(::Type{LratDeletedClauses}) = (;clause_ids = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:LratDeletedClauses}, _endpos::Int=0, _group::Bool=false)
    clause_ids = PB.BufferedVector{Int64}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, wire_type, clause_ids)
        else
            Base.skip(d, wire_type)
        end
    end
    return LratDeletedClauses(clause_ids[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::LratDeletedClauses)
    initpos = position(e.io)
    !isempty(x.clause_ids) && PB.encode(e, 1, x.clause_ids)
    return position(e.io) - initpos
end
function PB._encoded_size(x::LratDeletedClauses)
    encoded_size = 0
    !isempty(x.clause_ids) && (encoded_size += PB._encoded_size(x.clause_ids, 1))
    return encoded_size
end

struct var"LratInferredClause.RatInfo"
    resolvant_id::Int64
    unit_ids::Vector{Int64}
end
PB.default_values(::Type{var"LratInferredClause.RatInfo"}) = (;resolvant_id = zero(Int64), unit_ids = Vector{Int64}())
PB.field_numbers(::Type{var"LratInferredClause.RatInfo"}) = (;resolvant_id = 1, unit_ids = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"LratInferredClause.RatInfo"}, _endpos::Int=0, _group::Bool=false)
    resolvant_id = zero(Int64)
    unit_ids = PB.BufferedVector{Int64}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            resolvant_id = PB.decode(d, Int64)
        elseif field_number == 2
            PB.decode!(d, wire_type, unit_ids)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"LratInferredClause.RatInfo"(resolvant_id, unit_ids[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"LratInferredClause.RatInfo")
    initpos = position(e.io)
    x.resolvant_id != zero(Int64) && PB.encode(e, 1, x.resolvant_id)
    !isempty(x.unit_ids) && PB.encode(e, 2, x.unit_ids)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"LratInferredClause.RatInfo")
    encoded_size = 0
    x.resolvant_id != zero(Int64) && (encoded_size += PB._encoded_size(x.resolvant_id, 1))
    !isempty(x.unit_ids) && (encoded_size += PB._encoded_size(x.unit_ids, 2))
    return encoded_size
end

struct LratExportedClause
    clause_id::Int64
    literals::Vector{Int32}
end
PB.default_values(::Type{LratExportedClause}) = (;clause_id = zero(Int64), literals = Vector{Int32}())
PB.field_numbers(::Type{LratExportedClause}) = (;clause_id = 1, literals = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:LratExportedClause}, _endpos::Int=0, _group::Bool=false)
    clause_id = zero(Int64)
    literals = PB.BufferedVector{Int32}()
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            clause_id = PB.decode(d, Int64)
        elseif field_number == 2
            PB.decode!(d, wire_type, literals)
        else
            Base.skip(d, wire_type)
        end
    end
    return LratExportedClause(clause_id, literals[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::LratExportedClause)
    initpos = position(e.io)
    x.clause_id != zero(Int64) && PB.encode(e, 1, x.clause_id)
    !isempty(x.literals) && PB.encode(e, 2, x.literals)
    return position(e.io) - initpos
end
function PB._encoded_size(x::LratExportedClause)
    encoded_size = 0
    x.clause_id != zero(Int64) && (encoded_size += PB._encoded_size(x.clause_id, 1))
    !isempty(x.literals) && (encoded_size += PB._encoded_size(x.literals, 2))
    return encoded_size
end

struct LratInferredClause
    clause_id::Int64
    literals::Vector{Int32}
    unit_ids::Vector{Int64}
    rat_infos::Vector{var"LratInferredClause.RatInfo"}
    exported::Bool
end
PB.default_values(::Type{LratInferredClause}) = (;clause_id = zero(Int64), literals = Vector{Int32}(), unit_ids = Vector{Int64}(), rat_infos = Vector{var"LratInferredClause.RatInfo"}(), exported = false)
PB.field_numbers(::Type{LratInferredClause}) = (;clause_id = 1, literals = 2, unit_ids = 3, rat_infos = 4, exported = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:LratInferredClause}, _endpos::Int=0, _group::Bool=false)
    clause_id = zero(Int64)
    literals = PB.BufferedVector{Int32}()
    unit_ids = PB.BufferedVector{Int64}()
    rat_infos = PB.BufferedVector{var"LratInferredClause.RatInfo"}()
    exported = false
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            clause_id = PB.decode(d, Int64)
        elseif field_number == 2
            PB.decode!(d, wire_type, literals)
        elseif field_number == 3
            PB.decode!(d, wire_type, unit_ids)
        elseif field_number == 4
            PB.decode!(d, rat_infos)
        elseif field_number == 5
            exported = PB.decode(d, Bool)
        else
            Base.skip(d, wire_type)
        end
    end
    return LratInferredClause(clause_id, literals[], unit_ids[], rat_infos[], exported)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::LratInferredClause)
    initpos = position(e.io)
    x.clause_id != zero(Int64) && PB.encode(e, 1, x.clause_id)
    !isempty(x.literals) && PB.encode(e, 2, x.literals)
    !isempty(x.unit_ids) && PB.encode(e, 3, x.unit_ids)
    !isempty(x.rat_infos) && PB.encode(e, 4, x.rat_infos)
    x.exported != false && PB.encode(e, 5, x.exported)
    return position(e.io) - initpos
end
function PB._encoded_size(x::LratInferredClause)
    encoded_size = 0
    x.clause_id != zero(Int64) && (encoded_size += PB._encoded_size(x.clause_id, 1))
    !isempty(x.literals) && (encoded_size += PB._encoded_size(x.literals, 2))
    !isempty(x.unit_ids) && (encoded_size += PB._encoded_size(x.unit_ids, 3))
    !isempty(x.rat_infos) && (encoded_size += PB._encoded_size(x.rat_infos, 4))
    x.exported != false && (encoded_size += PB._encoded_size(x.exported, 5))
    return encoded_size
end

struct LratProofStep
    step::Union{Nothing,OneOf{<:Union{LratImportedClause,LratInferredClause,LratExportedClause,LratDeletedClauses}}}
end
PB.oneof_field_types(::Type{LratProofStep}) = (;
    step = (;imported_clause=LratImportedClause, inferred_clause=LratInferredClause, exported_clause=LratExportedClause, deleted_clauses=LratDeletedClauses),
)
PB.default_values(::Type{LratProofStep}) = (;imported_clause = nothing, inferred_clause = nothing, exported_clause = nothing, deleted_clauses = nothing)
PB.field_numbers(::Type{LratProofStep}) = (;imported_clause = 1, inferred_clause = 2, exported_clause = 3, deleted_clauses = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:LratProofStep}, _endpos::Int=0, _group::Bool=false)
    step = nothing
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            step = OneOf(:imported_clause, PB.decode(d, Ref{LratImportedClause}))
        elseif field_number == 2
            step = OneOf(:inferred_clause, PB.decode(d, Ref{LratInferredClause}))
        elseif field_number == 3
            step = OneOf(:exported_clause, PB.decode(d, Ref{LratExportedClause}))
        elseif field_number == 4
            step = OneOf(:deleted_clauses, PB.decode(d, Ref{LratDeletedClauses}))
        else
            Base.skip(d, wire_type)
        end
    end
    return LratProofStep(step)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::LratProofStep)
    initpos = position(e.io)
    if isnothing(x.step);
    elseif x.step.name === :imported_clause
        PB.encode(e, 1, x.step[]::LratImportedClause)
    elseif x.step.name === :inferred_clause
        PB.encode(e, 2, x.step[]::LratInferredClause)
    elseif x.step.name === :exported_clause
        PB.encode(e, 3, x.step[]::LratExportedClause)
    elseif x.step.name === :deleted_clauses
        PB.encode(e, 4, x.step[]::LratDeletedClauses)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::LratProofStep)
    encoded_size = 0
    if isnothing(x.step);
    elseif x.step.name === :imported_clause
        encoded_size += PB._encoded_size(x.step[]::LratImportedClause, 1)
    elseif x.step.name === :inferred_clause
        encoded_size += PB._encoded_size(x.step[]::LratInferredClause, 2)
    elseif x.step.name === :exported_clause
        encoded_size += PB._encoded_size(x.step[]::LratExportedClause, 3)
    elseif x.step.name === :deleted_clauses
        encoded_size += PB._encoded_size(x.step[]::LratDeletedClauses, 4)
    end
    return encoded_size
end
