# Copyright 2010-2025 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("//bazel:compilation_flags.bzl", "SAFE_FP_CODE")
load("//ortools/copts:configure_copts.bzl", "ORTOOLS_DEFAULT_COPTS", "ORTOOLS_DEFAULT_LINKOPTS", "ORTOOLS_TEST_COPTS")
load("//tools/testing:bintest.bzl", "bintest")

package(default_visibility = ["//visibility:public"])

### Arc Flow ###

cc_library(
    name = "arc_flow_builder",
    srcs = ["arc_flow_builder.cc"],
    hdrs = ["arc_flow_builder.h"],
    copts = SAFE_FP_CODE + ORTOOLS_DEFAULT_COPTS,
    linkopts = ORTOOLS_DEFAULT_LINKOPTS,
    deps = [
        "//ortools/base:stl_util",
        "//ortools/graph_base:topologicalsorter",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "arc_flow_builder_test",
    size = "small",
    srcs = ["arc_flow_builder_test.cc"],
    copts = ORTOOLS_TEST_COPTS,
    linkopts = ORTOOLS_DEFAULT_LINKOPTS,
    deps = [
        ":arc_flow_builder",
        "//ortools/base:gmock_main",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "arc_flow_solver",
    srcs = ["arc_flow_solver.cc"],
    hdrs = ["arc_flow_solver.h"],
    copts = ORTOOLS_DEFAULT_COPTS,
    linkopts = ORTOOLS_DEFAULT_LINKOPTS,
    deps = [
        ":arc_flow_builder",
        ":vector_bin_packing_cc_proto",
        "//ortools/base:file",
        "//ortools/base:timer",
        "//ortools/linear_solver:linear_solver_cc_proto",
        "//ortools/linear_solver:linear_solver_lib",
        "//ortools/linear_solver:linear_solver_sat",
        "//ortools/linear_solver:linear_solver_scip",
        "@abseil-cpp//absl/container:btree",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/time",
    ],
)

cc_test(
    name = "arc_flow_solver_test",
    size = "small",
    srcs = ["arc_flow_solver_test.cc"],
    copts = ORTOOLS_TEST_COPTS,
    linkopts = ORTOOLS_DEFAULT_LINKOPTS,
    deps = [
        ":arc_flow_solver",
        ":vector_bin_packing_cc_proto",
        "//ortools/base:gmock_main",
        "//ortools/base:parse_text_proto",
        "//ortools/linear_solver:linear_solver_sat",
    ],
)

### Vector Bin Packing ###

proto_library(
    name = "vector_bin_packing_proto",
    srcs = ["vector_bin_packing.proto"],
)

cc_proto_library(
    name = "vector_bin_packing_cc_proto",
    deps = [":vector_bin_packing_proto"],
)

cc_library(
    name = "vector_bin_packing_parser",
    srcs = ["vector_bin_packing_parser.cc"],
    hdrs = ["vector_bin_packing_parser.h"],
    copts = ORTOOLS_DEFAULT_COPTS,
    linkopts = ORTOOLS_DEFAULT_LINKOPTS,
    deps = [
        ":vector_bin_packing_cc_proto",
        "//ortools/util:filelineiter",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "vector_bin_packing_parser_test",
    size = "small",
    srcs = ["vector_bin_packing_parser_test.cc"],
    copts = ORTOOLS_TEST_COPTS,
    data = [
        "//ortools/packing/testdata:BPPC_5_0_10.vbp",
        "//ortools/packing/testdata:queen5_5.vbp",
    ],
    linkopts = ORTOOLS_DEFAULT_LINKOPTS,
    deps = [
        ":vector_bin_packing_cc_proto",
        ":vector_bin_packing_parser",
        "//ortools/base:gmock_main",
        "//ortools/util:data_path_resolver",
        "@abseil-cpp//absl/strings",
    ],
)

cc_binary(
    name = "vector_bin_packing",
    srcs = ["vector_bin_packing_main.cc"],
    copts = ORTOOLS_DEFAULT_COPTS,
    linkopts = ORTOOLS_DEFAULT_LINKOPTS,
    deps = [
        ":arc_flow_solver",
        ":vector_bin_packing_cc_proto",
        ":vector_bin_packing_parser",
        "//ortools/base",
        "//ortools/base:file",
        "//ortools/base:log_severity",
        "//ortools/linear_solver:linear_solver_lib",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/log:globals",
        "@abseil-cpp//absl/strings",
    ],
)

bintest(
    name = "vector_bin_packing_test",
    timeout = "long",
    srcs = ["vector_bin_packing.bintest"],
    named_data = {
        "vector_bin_packing": ":vector_bin_packing",
        "testdata": "//ortools/packing/testdata:1D__bpp_scholl__bin2data.N2W2B1R0.vbp",
    },
    tags = ["noci"],
)

### Multiple Dimension (non vector) Bin Packing ###

proto_library(
    name = "multiple_dimensions_bin_packing_proto",
    srcs = ["multiple_dimensions_bin_packing.proto"],
)

cc_proto_library(
    name = "multiple_dimensions_bin_packing_cc_proto",
    deps = [":multiple_dimensions_bin_packing_proto"],
)

cc_library(
    name = "binpacking_2d_parser",
    srcs = ["binpacking_2d_parser.cc"],
    hdrs = ["binpacking_2d_parser.h"],
    copts = ORTOOLS_DEFAULT_COPTS,
    linkopts = ORTOOLS_DEFAULT_LINKOPTS,
    deps = [
        ":multiple_dimensions_bin_packing_cc_proto",
        "//ortools/util:filelineiter",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "binpacking_2d_parser_test",
    size = "small",
    srcs = ["binpacking_2d_parser_test.cc"],
    copts = ORTOOLS_TEST_COPTS,
    data = ["//ortools/packing/testdata:Class_01.2bp"],
    linkopts = ORTOOLS_DEFAULT_LINKOPTS,
    deps = [
        ":binpacking_2d_parser",
        ":multiple_dimensions_bin_packing_cc_proto",
        "//ortools/base:gmock_main",
        "//ortools/util:data_path_resolver",
    ],
)
