cc_binary(
    name = "knapsack",
    srcs = ["knapsack.cc"],
    deps = [
        "//ortools/algorithms:knapsack_solver_lib",
    ],
)

cc_binary(
    name = "simple_knapsack_program",
    srcs = ["simple_knapsack_program.cc"],
    deps = [
        "//ortools/algorithms:knapsack_solver_lib",
    ],
)
