load(":code_samples.bzl", "code_sample_cc")

code_sample_cc(sample = "assignment_mip")

code_sample_cc(sample = "bin_packing_mip")

code_sample_cc(sample = "integer_programming_example")

code_sample_cc(sample = "linear_programming_example")

code_sample_cc(sample = "mip_var_array")

code_sample_cc(sample = "multiple_knapsack_mip")

code_sample_cc(sample = "simple_lp_program")

code_sample_cc(sample = "simple_mip_program")
