load(":code_samples.bzl", "code_sample_cc")

COPTS=["-std=c++17"]

code_sample_cc(sample = "assignment_sat")

code_sample_cc(sample = "binpacking_problem_sat")

code_sample_cc(sample = "bool_or_sample_sat")

code_sample_cc(sample = "channeling_sample_sat")

code_sample_cc(sample = "cp_is_fun_sat")

code_sample_cc(sample = "earliness_tardiness_cost_sample_sat")

code_sample_cc(sample = "interval_sample_sat")

code_sample_cc(sample = "literal_sample_sat")

code_sample_cc(sample = "multiple_knapsack_sat")

code_sample_cc(sample = "no_overlap_sample_sat")

code_sample_cc(sample = "optional_interval_sample_sat")

code_sample_cc(sample = "rabbits_and_pheasants_sat")

code_sample_cc(sample = "ranking_sample_sat")

code_sample_cc(sample = "reified_sample_sat")

code_sample_cc(sample = "search_for_all_solutions_sample_sat")

code_sample_cc(sample = "simple_sat_program")

code_sample_cc(sample = "solution_hinting_sample_sat")

code_sample_cc(sample = "solve_and_print_intermediate_solutions_sample_sat")

code_sample_cc(sample = "solve_with_time_limit_sample_sat")

code_sample_cc(sample = "step_function_sample_sat")

code_sample_cc(sample = "stop_after_n_solutions_sample_sat")
