# Autogenerated using ProtoBuf.jl v1.3.0
# original file: ortools/constraint_solver/routing_ils.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export RecreateParameters, SISRRuinStrategy, AbsencesBasedAcceptanceStrategy
export var"PerturbationStrategy.Value", var"RuinCompositionStrategy.Value"
export CoolingScheduleStrategy, RuinCompositionStrategy, var"CoolingScheduleStrategy.Value"
export GreedyDescentAcceptanceStrategy, MoreNodesPerformedAcceptanceStrategy
export RandomWalkRuinStrategy, PerturbationStrategy, SpatiallyCloseRoutesRuinStrategy
export AllNodesPerformedAcceptanceStrategy, RecreateStrategy
export SimulatedAnnealingAcceptanceStrategy, RuinStrategy, AcceptanceStrategy
export RuinRecreateParameters, IteratedLocalSearchParameters


struct RecreateParameters
    parameters::Union{Nothing,OneOf{<:Union{LocalCheapestInsertionParameters,SavingsParameters,GlobalCheapestInsertionParameters}}}
end
PB.oneof_field_types(::Type{RecreateParameters}) = (;
    parameters = (;local_cheapest_insertion=LocalCheapestInsertionParameters, savings=SavingsParameters, global_cheapest_insertion=GlobalCheapestInsertionParameters),
)
PB.default_values(::Type{RecreateParameters}) = (;local_cheapest_insertion = nothing, savings = nothing, global_cheapest_insertion = nothing)
PB.field_numbers(::Type{RecreateParameters}) = (;local_cheapest_insertion = 1, savings = 2, global_cheapest_insertion = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RecreateParameters}, _endpos::Int=0, _group::Bool=false)
    parameters = nothing
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            parameters = OneOf(:local_cheapest_insertion, PB.decode(d, Ref{LocalCheapestInsertionParameters}))
        elseif field_number == 2
            parameters = OneOf(:savings, PB.decode(d, Ref{SavingsParameters}))
        elseif field_number == 3
            parameters = OneOf(:global_cheapest_insertion, PB.decode(d, Ref{GlobalCheapestInsertionParameters}))
        else
            Base.skip(d, wire_type)
        end
    end
    return RecreateParameters(parameters)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RecreateParameters)
    initpos = position(e.io)
    if isnothing(x.parameters);
    elseif x.parameters.name === :local_cheapest_insertion
        PB.encode(e, 1, x.parameters[]::LocalCheapestInsertionParameters)
    elseif x.parameters.name === :savings
        PB.encode(e, 2, x.parameters[]::SavingsParameters)
    elseif x.parameters.name === :global_cheapest_insertion
        PB.encode(e, 3, x.parameters[]::GlobalCheapestInsertionParameters)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::RecreateParameters)
    encoded_size = 0
    if isnothing(x.parameters);
    elseif x.parameters.name === :local_cheapest_insertion
        encoded_size += PB._encoded_size(x.parameters[]::LocalCheapestInsertionParameters, 1)
    elseif x.parameters.name === :savings
        encoded_size += PB._encoded_size(x.parameters[]::SavingsParameters, 2)
    elseif x.parameters.name === :global_cheapest_insertion
        encoded_size += PB._encoded_size(x.parameters[]::GlobalCheapestInsertionParameters, 3)
    end
    return encoded_size
end

struct SISRRuinStrategy
    max_removed_sequence_size::UInt32
    avg_num_removed_visits::UInt32
    bypass_factor::Float64
end
PB.default_values(::Type{SISRRuinStrategy}) = (;max_removed_sequence_size = zero(UInt32), avg_num_removed_visits = zero(UInt32), bypass_factor = zero(Float64))
PB.field_numbers(::Type{SISRRuinStrategy}) = (;max_removed_sequence_size = 1, avg_num_removed_visits = 2, bypass_factor = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SISRRuinStrategy}, _endpos::Int=0, _group::Bool=false)
    max_removed_sequence_size = zero(UInt32)
    avg_num_removed_visits = zero(UInt32)
    bypass_factor = zero(Float64)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            max_removed_sequence_size = PB.decode(d, UInt32)
        elseif field_number == 2
            avg_num_removed_visits = PB.decode(d, UInt32)
        elseif field_number == 3
            bypass_factor = PB.decode(d, Float64)
        else
            Base.skip(d, wire_type)
        end
    end
    return SISRRuinStrategy(max_removed_sequence_size, avg_num_removed_visits, bypass_factor)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SISRRuinStrategy)
    initpos = position(e.io)
    x.max_removed_sequence_size != zero(UInt32) && PB.encode(e, 1, x.max_removed_sequence_size)
    x.avg_num_removed_visits != zero(UInt32) && PB.encode(e, 2, x.avg_num_removed_visits)
    x.bypass_factor !== zero(Float64) && PB.encode(e, 3, x.bypass_factor)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SISRRuinStrategy)
    encoded_size = 0
    x.max_removed_sequence_size != zero(UInt32) && (encoded_size += PB._encoded_size(x.max_removed_sequence_size, 1))
    x.avg_num_removed_visits != zero(UInt32) && (encoded_size += PB._encoded_size(x.avg_num_removed_visits, 2))
    x.bypass_factor !== zero(Float64) && (encoded_size += PB._encoded_size(x.bypass_factor, 3))
    return encoded_size
end

struct AbsencesBasedAcceptanceStrategy
    remove_route_with_lowest_absences::Bool
end
PB.default_values(::Type{AbsencesBasedAcceptanceStrategy}) = (;remove_route_with_lowest_absences = false)
PB.field_numbers(::Type{AbsencesBasedAcceptanceStrategy}) = (;remove_route_with_lowest_absences = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:AbsencesBasedAcceptanceStrategy}, _endpos::Int=0, _group::Bool=false)
    remove_route_with_lowest_absences = false
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            remove_route_with_lowest_absences = PB.decode(d, Bool)
        else
            Base.skip(d, wire_type)
        end
    end
    return AbsencesBasedAcceptanceStrategy(remove_route_with_lowest_absences)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::AbsencesBasedAcceptanceStrategy)
    initpos = position(e.io)
    x.remove_route_with_lowest_absences != false && PB.encode(e, 1, x.remove_route_with_lowest_absences)
    return position(e.io) - initpos
end
function PB._encoded_size(x::AbsencesBasedAcceptanceStrategy)
    encoded_size = 0
    x.remove_route_with_lowest_absences != false && (encoded_size += PB._encoded_size(x.remove_route_with_lowest_absences, 1))
    return encoded_size
end

@enumx var"PerturbationStrategy.Value" UNSET=0 RUIN_AND_RECREATE=1

@enumx var"RuinCompositionStrategy.Value" UNSET=0 RUN_ALL_SEQUENTIALLY=1 RUN_ALL_RANDOMLY=2 RUN_ONE_RANDOMLY=3

struct CoolingScheduleStrategy end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:CoolingScheduleStrategy}, _endpos::Int=0, _group::Bool=false)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return CoolingScheduleStrategy()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::CoolingScheduleStrategy)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::CoolingScheduleStrategy)
    encoded_size = 0
    return encoded_size
end

struct RuinCompositionStrategy end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RuinCompositionStrategy}, _endpos::Int=0, _group::Bool=false)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return RuinCompositionStrategy()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RuinCompositionStrategy)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RuinCompositionStrategy)
    encoded_size = 0
    return encoded_size
end

@enumx var"CoolingScheduleStrategy.Value" UNSET=0 EXPONENTIAL=1 LINEAR=2

struct GreedyDescentAcceptanceStrategy end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:GreedyDescentAcceptanceStrategy}, _endpos::Int=0, _group::Bool=false)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return GreedyDescentAcceptanceStrategy()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::GreedyDescentAcceptanceStrategy)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::GreedyDescentAcceptanceStrategy)
    encoded_size = 0
    return encoded_size
end

struct MoreNodesPerformedAcceptanceStrategy end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:MoreNodesPerformedAcceptanceStrategy}, _endpos::Int=0, _group::Bool=false)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return MoreNodesPerformedAcceptanceStrategy()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::MoreNodesPerformedAcceptanceStrategy)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::MoreNodesPerformedAcceptanceStrategy)
    encoded_size = 0
    return encoded_size
end

struct RandomWalkRuinStrategy
    num_removed_visits::UInt32
end
PB.default_values(::Type{RandomWalkRuinStrategy}) = (;num_removed_visits = zero(UInt32))
PB.field_numbers(::Type{RandomWalkRuinStrategy}) = (;num_removed_visits = 7)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RandomWalkRuinStrategy}, _endpos::Int=0, _group::Bool=false)
    num_removed_visits = zero(UInt32)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 7
            num_removed_visits = PB.decode(d, UInt32)
        else
            Base.skip(d, wire_type)
        end
    end
    return RandomWalkRuinStrategy(num_removed_visits)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RandomWalkRuinStrategy)
    initpos = position(e.io)
    x.num_removed_visits != zero(UInt32) && PB.encode(e, 7, x.num_removed_visits)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RandomWalkRuinStrategy)
    encoded_size = 0
    x.num_removed_visits != zero(UInt32) && (encoded_size += PB._encoded_size(x.num_removed_visits, 7))
    return encoded_size
end

struct PerturbationStrategy end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:PerturbationStrategy}, _endpos::Int=0, _group::Bool=false)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return PerturbationStrategy()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::PerturbationStrategy)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::PerturbationStrategy)
    encoded_size = 0
    return encoded_size
end

struct SpatiallyCloseRoutesRuinStrategy
    num_ruined_routes::UInt32
end
PB.default_values(::Type{SpatiallyCloseRoutesRuinStrategy}) = (;num_ruined_routes = zero(UInt32))
PB.field_numbers(::Type{SpatiallyCloseRoutesRuinStrategy}) = (;num_ruined_routes = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SpatiallyCloseRoutesRuinStrategy}, _endpos::Int=0, _group::Bool=false)
    num_ruined_routes = zero(UInt32)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 3
            num_ruined_routes = PB.decode(d, UInt32)
        else
            Base.skip(d, wire_type)
        end
    end
    return SpatiallyCloseRoutesRuinStrategy(num_ruined_routes)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SpatiallyCloseRoutesRuinStrategy)
    initpos = position(e.io)
    x.num_ruined_routes != zero(UInt32) && PB.encode(e, 3, x.num_ruined_routes)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SpatiallyCloseRoutesRuinStrategy)
    encoded_size = 0
    x.num_ruined_routes != zero(UInt32) && (encoded_size += PB._encoded_size(x.num_ruined_routes, 3))
    return encoded_size
end

struct AllNodesPerformedAcceptanceStrategy end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:AllNodesPerformedAcceptanceStrategy}, _endpos::Int=0, _group::Bool=false)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return AllNodesPerformedAcceptanceStrategy()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::AllNodesPerformedAcceptanceStrategy)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::AllNodesPerformedAcceptanceStrategy)
    encoded_size = 0
    return encoded_size
end

struct RecreateStrategy
    heuristic::var"FirstSolutionStrategy.Value".T
    parameters::Union{Nothing,RecreateParameters}
end
PB.default_values(::Type{RecreateStrategy}) = (;heuristic = var"FirstSolutionStrategy.Value".UNSET, parameters = nothing)
PB.field_numbers(::Type{RecreateStrategy}) = (;heuristic = 1, parameters = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RecreateStrategy}, _endpos::Int=0, _group::Bool=false)
    heuristic = var"FirstSolutionStrategy.Value".UNSET
    parameters = Ref{Union{Nothing,RecreateParameters}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            heuristic = PB.decode(d, var"FirstSolutionStrategy.Value".T)
        elseif field_number == 2
            PB.decode!(d, parameters)
        else
            Base.skip(d, wire_type)
        end
    end
    return RecreateStrategy(heuristic, parameters[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RecreateStrategy)
    initpos = position(e.io)
    x.heuristic != var"FirstSolutionStrategy.Value".UNSET && PB.encode(e, 1, x.heuristic)
    !isnothing(x.parameters) && PB.encode(e, 2, x.parameters)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RecreateStrategy)
    encoded_size = 0
    x.heuristic != var"FirstSolutionStrategy.Value".UNSET && (encoded_size += PB._encoded_size(x.heuristic, 1))
    !isnothing(x.parameters) && (encoded_size += PB._encoded_size(x.parameters, 2))
    return encoded_size
end

struct SimulatedAnnealingAcceptanceStrategy
    cooling_schedule_strategy::var"CoolingScheduleStrategy.Value".T
    initial_temperature::Float64
    final_temperature::Float64
    automatic_temperatures::Bool
end
PB.default_values(::Type{SimulatedAnnealingAcceptanceStrategy}) = (;cooling_schedule_strategy = var"CoolingScheduleStrategy.Value".UNSET, initial_temperature = zero(Float64), final_temperature = zero(Float64), automatic_temperatures = false)
PB.field_numbers(::Type{SimulatedAnnealingAcceptanceStrategy}) = (;cooling_schedule_strategy = 1, initial_temperature = 2, final_temperature = 3, automatic_temperatures = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SimulatedAnnealingAcceptanceStrategy}, _endpos::Int=0, _group::Bool=false)
    cooling_schedule_strategy = var"CoolingScheduleStrategy.Value".UNSET
    initial_temperature = zero(Float64)
    final_temperature = zero(Float64)
    automatic_temperatures = false
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            cooling_schedule_strategy = PB.decode(d, var"CoolingScheduleStrategy.Value".T)
        elseif field_number == 2
            initial_temperature = PB.decode(d, Float64)
        elseif field_number == 3
            final_temperature = PB.decode(d, Float64)
        elseif field_number == 4
            automatic_temperatures = PB.decode(d, Bool)
        else
            Base.skip(d, wire_type)
        end
    end
    return SimulatedAnnealingAcceptanceStrategy(cooling_schedule_strategy, initial_temperature, final_temperature, automatic_temperatures)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SimulatedAnnealingAcceptanceStrategy)
    initpos = position(e.io)
    x.cooling_schedule_strategy != var"CoolingScheduleStrategy.Value".UNSET && PB.encode(e, 1, x.cooling_schedule_strategy)
    x.initial_temperature !== zero(Float64) && PB.encode(e, 2, x.initial_temperature)
    x.final_temperature !== zero(Float64) && PB.encode(e, 3, x.final_temperature)
    x.automatic_temperatures != false && PB.encode(e, 4, x.automatic_temperatures)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SimulatedAnnealingAcceptanceStrategy)
    encoded_size = 0
    x.cooling_schedule_strategy != var"CoolingScheduleStrategy.Value".UNSET && (encoded_size += PB._encoded_size(x.cooling_schedule_strategy, 1))
    x.initial_temperature !== zero(Float64) && (encoded_size += PB._encoded_size(x.initial_temperature, 2))
    x.final_temperature !== zero(Float64) && (encoded_size += PB._encoded_size(x.final_temperature, 3))
    x.automatic_temperatures != false && (encoded_size += PB._encoded_size(x.automatic_temperatures, 4))
    return encoded_size
end

struct RuinStrategy
    strategy::Union{Nothing,OneOf{<:Union{SpatiallyCloseRoutesRuinStrategy,RandomWalkRuinStrategy,SISRRuinStrategy}}}
end
PB.oneof_field_types(::Type{RuinStrategy}) = (;
    strategy = (;spatially_close_routes=SpatiallyCloseRoutesRuinStrategy, random_walk=RandomWalkRuinStrategy, sisr=SISRRuinStrategy),
)
PB.default_values(::Type{RuinStrategy}) = (;spatially_close_routes = nothing, random_walk = nothing, sisr = nothing)
PB.field_numbers(::Type{RuinStrategy}) = (;spatially_close_routes = 1, random_walk = 2, sisr = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RuinStrategy}, _endpos::Int=0, _group::Bool=false)
    strategy = nothing
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            strategy = OneOf(:spatially_close_routes, PB.decode(d, Ref{SpatiallyCloseRoutesRuinStrategy}))
        elseif field_number == 2
            strategy = OneOf(:random_walk, PB.decode(d, Ref{RandomWalkRuinStrategy}))
        elseif field_number == 3
            strategy = OneOf(:sisr, PB.decode(d, Ref{SISRRuinStrategy}))
        else
            Base.skip(d, wire_type)
        end
    end
    return RuinStrategy(strategy)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RuinStrategy)
    initpos = position(e.io)
    if isnothing(x.strategy);
    elseif x.strategy.name === :spatially_close_routes
        PB.encode(e, 1, x.strategy[]::SpatiallyCloseRoutesRuinStrategy)
    elseif x.strategy.name === :random_walk
        PB.encode(e, 2, x.strategy[]::RandomWalkRuinStrategy)
    elseif x.strategy.name === :sisr
        PB.encode(e, 3, x.strategy[]::SISRRuinStrategy)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::RuinStrategy)
    encoded_size = 0
    if isnothing(x.strategy);
    elseif x.strategy.name === :spatially_close_routes
        encoded_size += PB._encoded_size(x.strategy[]::SpatiallyCloseRoutesRuinStrategy, 1)
    elseif x.strategy.name === :random_walk
        encoded_size += PB._encoded_size(x.strategy[]::RandomWalkRuinStrategy, 2)
    elseif x.strategy.name === :sisr
        encoded_size += PB._encoded_size(x.strategy[]::SISRRuinStrategy, 3)
    end
    return encoded_size
end

struct AcceptanceStrategy
    strategy::Union{Nothing,OneOf{<:Union{GreedyDescentAcceptanceStrategy,SimulatedAnnealingAcceptanceStrategy,AllNodesPerformedAcceptanceStrategy,MoreNodesPerformedAcceptanceStrategy,AbsencesBasedAcceptanceStrategy}}}
end
PB.oneof_field_types(::Type{AcceptanceStrategy}) = (;
    strategy = (;greedy_descent=GreedyDescentAcceptanceStrategy, simulated_annealing=SimulatedAnnealingAcceptanceStrategy, all_nodes_performed=AllNodesPerformedAcceptanceStrategy, more_nodes_performed=MoreNodesPerformedAcceptanceStrategy, absences_based=AbsencesBasedAcceptanceStrategy),
)
PB.default_values(::Type{AcceptanceStrategy}) = (;greedy_descent = nothing, simulated_annealing = nothing, all_nodes_performed = nothing, more_nodes_performed = nothing, absences_based = nothing)
PB.field_numbers(::Type{AcceptanceStrategy}) = (;greedy_descent = 1, simulated_annealing = 2, all_nodes_performed = 3, more_nodes_performed = 4, absences_based = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:AcceptanceStrategy}, _endpos::Int=0, _group::Bool=false)
    strategy = nothing
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            strategy = OneOf(:greedy_descent, PB.decode(d, Ref{GreedyDescentAcceptanceStrategy}))
        elseif field_number == 2
            strategy = OneOf(:simulated_annealing, PB.decode(d, Ref{SimulatedAnnealingAcceptanceStrategy}))
        elseif field_number == 3
            strategy = OneOf(:all_nodes_performed, PB.decode(d, Ref{AllNodesPerformedAcceptanceStrategy}))
        elseif field_number == 4
            strategy = OneOf(:more_nodes_performed, PB.decode(d, Ref{MoreNodesPerformedAcceptanceStrategy}))
        elseif field_number == 5
            strategy = OneOf(:absences_based, PB.decode(d, Ref{AbsencesBasedAcceptanceStrategy}))
        else
            Base.skip(d, wire_type)
        end
    end
    return AcceptanceStrategy(strategy)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::AcceptanceStrategy)
    initpos = position(e.io)
    if isnothing(x.strategy);
    elseif x.strategy.name === :greedy_descent
        PB.encode(e, 1, x.strategy[]::GreedyDescentAcceptanceStrategy)
    elseif x.strategy.name === :simulated_annealing
        PB.encode(e, 2, x.strategy[]::SimulatedAnnealingAcceptanceStrategy)
    elseif x.strategy.name === :all_nodes_performed
        PB.encode(e, 3, x.strategy[]::AllNodesPerformedAcceptanceStrategy)
    elseif x.strategy.name === :more_nodes_performed
        PB.encode(e, 4, x.strategy[]::MoreNodesPerformedAcceptanceStrategy)
    elseif x.strategy.name === :absences_based
        PB.encode(e, 5, x.strategy[]::AbsencesBasedAcceptanceStrategy)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::AcceptanceStrategy)
    encoded_size = 0
    if isnothing(x.strategy);
    elseif x.strategy.name === :greedy_descent
        encoded_size += PB._encoded_size(x.strategy[]::GreedyDescentAcceptanceStrategy, 1)
    elseif x.strategy.name === :simulated_annealing
        encoded_size += PB._encoded_size(x.strategy[]::SimulatedAnnealingAcceptanceStrategy, 2)
    elseif x.strategy.name === :all_nodes_performed
        encoded_size += PB._encoded_size(x.strategy[]::AllNodesPerformedAcceptanceStrategy, 3)
    elseif x.strategy.name === :more_nodes_performed
        encoded_size += PB._encoded_size(x.strategy[]::MoreNodesPerformedAcceptanceStrategy, 4)
    elseif x.strategy.name === :absences_based
        encoded_size += PB._encoded_size(x.strategy[]::AbsencesBasedAcceptanceStrategy, 5)
    end
    return encoded_size
end

struct RuinRecreateParameters
    ruin_strategies::Vector{RuinStrategy}
    ruin_composition_strategy::var"RuinCompositionStrategy.Value".T
    recreate_strategy::Union{Nothing,RecreateStrategy}
    route_selection_neighbors_ratio::Float64
    route_selection_min_neighbors::UInt32
    route_selection_max_neighbors::UInt32
end
PB.default_values(::Type{RuinRecreateParameters}) = (;ruin_strategies = Vector{RuinStrategy}(), ruin_composition_strategy = var"RuinCompositionStrategy.Value".UNSET, recreate_strategy = nothing, route_selection_neighbors_ratio = zero(Float64), route_selection_min_neighbors = zero(UInt32), route_selection_max_neighbors = zero(UInt32))
PB.field_numbers(::Type{RuinRecreateParameters}) = (;ruin_strategies = 1, ruin_composition_strategy = 2, recreate_strategy = 3, route_selection_neighbors_ratio = 4, route_selection_min_neighbors = 5, route_selection_max_neighbors = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RuinRecreateParameters}, _endpos::Int=0, _group::Bool=false)
    ruin_strategies = PB.BufferedVector{RuinStrategy}()
    ruin_composition_strategy = var"RuinCompositionStrategy.Value".UNSET
    recreate_strategy = Ref{Union{Nothing,RecreateStrategy}}(nothing)
    route_selection_neighbors_ratio = zero(Float64)
    route_selection_min_neighbors = zero(UInt32)
    route_selection_max_neighbors = zero(UInt32)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, ruin_strategies)
        elseif field_number == 2
            ruin_composition_strategy = PB.decode(d, var"RuinCompositionStrategy.Value".T)
        elseif field_number == 3
            PB.decode!(d, recreate_strategy)
        elseif field_number == 4
            route_selection_neighbors_ratio = PB.decode(d, Float64)
        elseif field_number == 5
            route_selection_min_neighbors = PB.decode(d, UInt32)
        elseif field_number == 6
            route_selection_max_neighbors = PB.decode(d, UInt32)
        else
            Base.skip(d, wire_type)
        end
    end
    return RuinRecreateParameters(ruin_strategies[], ruin_composition_strategy, recreate_strategy[], route_selection_neighbors_ratio, route_selection_min_neighbors, route_selection_max_neighbors)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RuinRecreateParameters)
    initpos = position(e.io)
    !isempty(x.ruin_strategies) && PB.encode(e, 1, x.ruin_strategies)
    x.ruin_composition_strategy != var"RuinCompositionStrategy.Value".UNSET && PB.encode(e, 2, x.ruin_composition_strategy)
    !isnothing(x.recreate_strategy) && PB.encode(e, 3, x.recreate_strategy)
    x.route_selection_neighbors_ratio !== zero(Float64) && PB.encode(e, 4, x.route_selection_neighbors_ratio)
    x.route_selection_min_neighbors != zero(UInt32) && PB.encode(e, 5, x.route_selection_min_neighbors)
    x.route_selection_max_neighbors != zero(UInt32) && PB.encode(e, 6, x.route_selection_max_neighbors)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RuinRecreateParameters)
    encoded_size = 0
    !isempty(x.ruin_strategies) && (encoded_size += PB._encoded_size(x.ruin_strategies, 1))
    x.ruin_composition_strategy != var"RuinCompositionStrategy.Value".UNSET && (encoded_size += PB._encoded_size(x.ruin_composition_strategy, 2))
    !isnothing(x.recreate_strategy) && (encoded_size += PB._encoded_size(x.recreate_strategy, 3))
    x.route_selection_neighbors_ratio !== zero(Float64) && (encoded_size += PB._encoded_size(x.route_selection_neighbors_ratio, 4))
    x.route_selection_min_neighbors != zero(UInt32) && (encoded_size += PB._encoded_size(x.route_selection_min_neighbors, 5))
    x.route_selection_max_neighbors != zero(UInt32) && (encoded_size += PB._encoded_size(x.route_selection_max_neighbors, 6))
    return encoded_size
end

struct IteratedLocalSearchParameters
    perturbation_strategy::var"PerturbationStrategy.Value".T
    ruin_recreate_parameters::Union{Nothing,RuinRecreateParameters}
    improve_perturbed_solution::Bool
    reference_solution_acceptance_strategy::Union{Nothing,AcceptanceStrategy}
    best_solution_acceptance_strategy::Union{Nothing,AcceptanceStrategy}
end
PB.default_values(::Type{IteratedLocalSearchParameters}) = (;perturbation_strategy = var"PerturbationStrategy.Value".UNSET, ruin_recreate_parameters = nothing, improve_perturbed_solution = false, reference_solution_acceptance_strategy = nothing, best_solution_acceptance_strategy = nothing)
PB.field_numbers(::Type{IteratedLocalSearchParameters}) = (;perturbation_strategy = 1, ruin_recreate_parameters = 2, improve_perturbed_solution = 3, reference_solution_acceptance_strategy = 4, best_solution_acceptance_strategy = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:IteratedLocalSearchParameters}, _endpos::Int=0, _group::Bool=false)
    perturbation_strategy = var"PerturbationStrategy.Value".UNSET
    ruin_recreate_parameters = Ref{Union{Nothing,RuinRecreateParameters}}(nothing)
    improve_perturbed_solution = false
    reference_solution_acceptance_strategy = Ref{Union{Nothing,AcceptanceStrategy}}(nothing)
    best_solution_acceptance_strategy = Ref{Union{Nothing,AcceptanceStrategy}}(nothing)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            perturbation_strategy = PB.decode(d, var"PerturbationStrategy.Value".T)
        elseif field_number == 2
            PB.decode!(d, ruin_recreate_parameters)
        elseif field_number == 3
            improve_perturbed_solution = PB.decode(d, Bool)
        elseif field_number == 4
            PB.decode!(d, reference_solution_acceptance_strategy)
        elseif field_number == 5
            PB.decode!(d, best_solution_acceptance_strategy)
        else
            Base.skip(d, wire_type)
        end
    end
    return IteratedLocalSearchParameters(perturbation_strategy, ruin_recreate_parameters[], improve_perturbed_solution, reference_solution_acceptance_strategy[], best_solution_acceptance_strategy[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::IteratedLocalSearchParameters)
    initpos = position(e.io)
    x.perturbation_strategy != var"PerturbationStrategy.Value".UNSET && PB.encode(e, 1, x.perturbation_strategy)
    !isnothing(x.ruin_recreate_parameters) && PB.encode(e, 2, x.ruin_recreate_parameters)
    x.improve_perturbed_solution != false && PB.encode(e, 3, x.improve_perturbed_solution)
    !isnothing(x.reference_solution_acceptance_strategy) && PB.encode(e, 4, x.reference_solution_acceptance_strategy)
    !isnothing(x.best_solution_acceptance_strategy) && PB.encode(e, 5, x.best_solution_acceptance_strategy)
    return position(e.io) - initpos
end
function PB._encoded_size(x::IteratedLocalSearchParameters)
    encoded_size = 0
    x.perturbation_strategy != var"PerturbationStrategy.Value".UNSET && (encoded_size += PB._encoded_size(x.perturbation_strategy, 1))
    !isnothing(x.ruin_recreate_parameters) && (encoded_size += PB._encoded_size(x.ruin_recreate_parameters, 2))
    x.improve_perturbed_solution != false && (encoded_size += PB._encoded_size(x.improve_perturbed_solution, 3))
    !isnothing(x.reference_solution_acceptance_strategy) && (encoded_size += PB._encoded_size(x.reference_solution_acceptance_strategy, 4))
    !isnothing(x.best_solution_acceptance_strategy) && (encoded_size += PB._encoded_size(x.best_solution_acceptance_strategy, 5))
    return encoded_size
end
