# Description:
#   These files tells minizinc how to translate a minizinc file (.mzn)
#   into a flatzinc one (.fzn).
#
#   The name of each file is fixed, and each should describe how to
#   interpret a given predicate.

package(default_visibility = ["//visibility:public"])

# Definition files (.mzn).

filegroup(
    name = "minizinc_sat_files",
    srcs = glob(["*.mzn"]),
)
