if(NOT DEFINED CP_MODEL_PROTO OR NOT DEFINED SAT_PARAMETERS_PROTO OR
   NOT DEFINED TEMPLATE_FILE OR NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "embed_proto.cmake missing required arguments.")
endif()

file(READ "${CP_MODEL_PROTO}" CP_MODEL_PROTO_TEXT)
file(READ "${SAT_PARAMETERS_PROTO}" SAT_PARAMETERS_PROTO_TEXT)

configure_file("${TEMPLATE_FILE}" "${OUTPUT_FILE}" @ONLY)
