load(":code_samples.bzl", "code_sample_cc")

code_sample_cc(sample = "minimal_jobshop_cp")

code_sample_cc(sample = "nurses_cp")

code_sample_cc(sample = "rabbits_and_pheasants_cp")

code_sample_cc(sample = "simple_cp_program")

code_sample_cc(sample = "simple_ls_program")

code_sample_cc(sample = "simple_routing_program")

code_sample_cc(sample = "tsp")

code_sample_cc(sample = "tsp_circuit_board")

code_sample_cc(sample = "tsp_cities")

code_sample_cc(sample = "tsp_distance_matrix")

code_sample_cc(sample = "vrp_capacity")

code_sample_cc(sample = "vrp")

code_sample_cc(sample = "vrp_drop_nodes")

code_sample_cc(sample = "vrp_global_span")

code_sample_cc(sample = "vrp_initial_routes")

code_sample_cc(sample = "vrp_pickup_delivery")

code_sample_cc(sample = "vrp_pickup_delivery_fifo")

code_sample_cc(sample = "vrp_pickup_delivery_lifo")

code_sample_cc(sample = "vrp_resources")

code_sample_cc(sample = "vrp_starts_ends")

code_sample_cc(sample = "vrp_time_windows")

code_sample_cc(sample = "vrp_with_time_limit")
