# ref: https://github.com/docker-library/official-images
name: amd64 Web

on: [push, pull_request, workflow_dispatch]

jobs:
  emscripten:
    name: Linux • Emscripten
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check docker
      run: |
        docker info
        docker buildx ls
    - name: Build env image
      run: make --directory=cmake web_env
    - name: Build devel project
      run: make --directory=cmake web_devel
    - name: Build project
      run: make --directory=cmake web_build
    - name: Test project
      run: make --directory=cmake web_test
