# ref: https://github.com/actions/runner-images
name: amd64 Linux CMake GLPK ON

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    name: Linux • CMake • GLPK ON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check cmake
        run: cmake --version
      - name: Configure
        run: >
          cmake -S. -Bbuild
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_DEPS=ON
          -DUSE_SCIP=OFF -DUSE_COINOR=OFF
          -DUSE_GLPK=ON
      - name: Build
        run: >
          cmake --build build
          --config Release
          --target all
          -v -j2
      - name: Test
        run: >
          CTEST_OUTPUT_ON_FAILURE=1
          cmake --build build
          --config Release
          --target test
          -v
      - name: Install
        run: >
          cmake --build build
          --config Release
          --target install
          -v
          -- DESTDIR=install
