# Test or-tools using system wide install dependencies.
name: amd64 Linux CMake System Dependencies

on: [push, pull_request, workflow_dispatch]

jobs:
  native:
    strategy:
      matrix:
        distro: [system_deps]
        lang: [cpp, python, dotnet, java]
      fail-fast: false
    name: Archlinux • CMake • ${{ matrix.lang }} • BUILD_DEPS OFF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build base image
        run: make --directory=cmake ${{ matrix.distro }}_base
      - name: Build env image
        run: make --directory=cmake ${{ matrix.distro }}_${{ matrix.lang }}_env
      - name: Build devel image
        run: make --directory=cmake ${{ matrix.distro }}_${{ matrix.lang }}_devel
      - name: Build project
        run: make --directory=cmake ${{ matrix.distro }}_${{ matrix.lang }}_build
      - name: Test project
        run: make --directory=cmake ${{ matrix.distro }}_${{ matrix.lang }}_test

      - name: Build Install env image
        run: make --directory=cmake ${{ matrix.distro }}_${{ matrix.lang }}_install_env
      - name: Build Install devel image
        run: make --directory=cmake ${{ matrix.distro }}_${{ matrix.lang }}_install_devel
      - name: Build Install
        run: make --directory=cmake ${{ matrix.distro }}_${{ matrix.lang }}_install_build
      - name: Test Install
        run: make --directory=cmake ${{ matrix.distro }}_${{ matrix.lang }}_install_test

# TODO(user): Add macOS + brew job
# TODO(user): Add Windows + choco/vcpkg job

