# ref: https://github.com/actions/runner-images
name: amd64 Windows Bazel

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        runner: [windows-2022]
        python: [
          {version: '3.9'},
          {version: '3.10'},
          {version: '3.11'},
          {version: '3.12'},
        ]
      fail-fast: false # Don't cancel all jobs if one fails.
    name: ${{ matrix.runner }} • Bazel • Python-${{ matrix.python.version }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check java
        run: java -version
      - name: Check mvn
        run: mvn --version
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
      - name: Check Python
        run: python --version
      - name: Install Bazel
        run: choco install bazel
      - name: Check Bazel
        run: bazel version
      - name: Build
        run: >
          bazel build
          -c opt
          --subcommands=pretty_print
          //ortools/... //examples/...
      - name: Test
        run: >
          bazel test
          -c opt
          --test_output=errors
          //ortools/... //examples/...
