name: amd64 FreeBSD CMake

on: [push, pull_request, workflow_dispatch]

# Only macos-12 runner provide virtualisation with vagrant/virtualbox installed.
# ref: https://github.com/actions/runner-images/tree/main/images/macos
# ref: https://app.vagrantup.com/generic/boxes/freebsd13
jobs:
  vagrant:
    strategy:
      fail-fast: false
      matrix:
        distro: [freebsd]
        lang: [cpp, python]
        allow_failure: [false]
        include:
        - distro: freebsd
          lang: dotnet
          allow_failure: true
        - distro: freebsd
          lang: java
          allow_failure: true
    name: FreeBSD • CMake • ${{ matrix.lang }}
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: vagrant version
        run: Vagrant --version
      - name: VirtualBox version
        run: virtualbox -h
      - name: Build
        run: make --directory=cmake ${{ matrix.distro }}_${{ matrix.lang }}
