#!/usr/bin/env python3
# Copyright 2010-2025 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import overload

class Domain:
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @staticmethod
    def AllValues() -> Domain: ...
    def FlattenedIntervals(self) -> list[int]: ...
    @staticmethod
    def FromFlatIntervals(flat_intervals: list[int]) -> Domain: ...
    @staticmethod
    def FromIntervals(intervals: list[list[int]]) -> Domain: ...
    @staticmethod
    def FromValues(values: list[int]) -> Domain: ...
    def addition_with(self, domain: Domain) -> Domain: ...
    @staticmethod
    def all_values() -> Domain: ...
    def complement(self) -> Domain: ...
    def contains(self, value: int) -> bool: ...
    @overload
    def continuous_multiplication_by(self, domain: Domain) -> Domain: ...
    @overload
    def continuous_multiplication_by(self, coeff: int) -> Domain: ...
    def division_by(self, coeff: int) -> Domain: ...
    def division_by_superset(self, divisor: Domain) -> Domain: ...
    @staticmethod
    def empty() -> Domain: ...
    def flattened_intervals(self) -> list[int]: ...
    @staticmethod
    def from_flat_intervals(flat_intervals: list[int]) -> Domain: ...
    @staticmethod
    def from_intervals(intervals: list[list[int]]) -> Domain: ...
    @staticmethod
    def from_values(values: list[int]) -> Domain: ...
    @staticmethod
    def greater_or_equal(value: int) -> Domain: ...
    def intersection_with(self, domain: Domain) -> Domain: ...
    def is_empty(self) -> bool: ...
    def is_included_in(self, domain: Domain) -> bool: ...
    @staticmethod
    def lower_or_equal(value: int) -> Domain: ...
    def max(self) -> int: ...
    def min(self) -> int: ...
    def negation(self) -> Domain: ...
    def overlaps_with(self, domain: Domain) -> bool: ...
    def positive_modulo_by_superset(self, modulo: Domain) -> Domain: ...
    def size(self) -> int: ...
    def union_with(self, domain: Domain) -> Domain: ...
    def value_at_or_after(self, value: int) -> int: ...
    def value_at_or_before(self, value: int) -> int: ...
    def values(self) -> list[int]: ...
    def __copy__(self) -> Domain: ...
    def __deepcopy__(self, arg0: dict) -> Domain: ...
    def __eq__(self, arg0: Domain) -> bool: ...
