#ifndef OR_TOOLS_BASE_ADJUSTABLE_PRIORITY_QUEUE_INL_H_
#define OR_TOOLS_BASE_ADJUSTABLE_PRIORITY_QUEUE_INL_H_

#include "base/adjustable_priority_queue.h"

#endif  // OR_TOOLS_BASE_ADJUSTABLE_PRIORITY_QUEUE_INL_H_
