package(default_visibility = ["//visibility:public"])

cc_library(
    name = 'base',
    srcs = glob(['*.cc']),
    hdrs = glob(['*.h']),
    deps = ["//external:gflags",
            "//external:protobuf",],
)
