package(default_visibility = ["//visibility:public"])

cc_library(
    name = 'base',
    srcs = glob(['*.cc']),
    hdrs = glob(['*.h']),
    deps = ["@com_github_gflags_gflags//:gflags",
            "@com_google_protobuf_cc//:protobuf",],
)
