// Copyright 2010-2025 Google LLC
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package statusstreaming translates ortools/util StatusProto to Go errors.
//
// Errors generated by ToError() use error wrapping as described in
// https://blog.golang.org/go1.13-errors. The function errors.Is() can be used
// by with ErrXxx errors to test the type of error.
//
// The function ErrorCode() can be used to get the code of the error. It also
// tests if one of the wrapped error has been generated by ToError() even when
// the code does not match a known value defined by ErrXxx constants.
package statusstreaming

import (
	"errors"
	"fmt"

	spb "ortools/util/status_go_proto"
)

// code are the C++ absl::Status::code() values.
type code int32

// value returns the underlying integer value.
func (c code) value() int32 {
	return int32(c)
}

var (
	okCode                 = code(0)
	cancelledCode          = code(1)
	unknownCode            = code(2)
	invalidArgumentCode    = code(3)
	deadlineExceededCode   = code(4)
	notFoundCode           = code(5)
	alreadyExistsCode      = code(6)
	permissionDeniedCode   = code(7)
	unauthenticatedCode    = code(16)
	resourceExhaustedCode  = code(8)
	failedPreconditionCode = code(9)
	abortedCode            = code(10)
	outOfRangeCode         = code(11)
	unimplementedCode      = code(12)
	internalCode           = code(13)
	unavailableCode        = code(14)
	dataLossCode           = code(15)
)

// codeName contains a name for each value of code
var codeName = map[code]string{
	okCode:                 "OK",
	cancelledCode:          "CANCELLED",
	unknownCode:            "UNKNOWN",
	invalidArgumentCode:    "INVALID_ARGUMENT",
	deadlineExceededCode:   "DEADLINE_EXCEEDED",
	notFoundCode:           "NOT_FOUND",
	alreadyExistsCode:      "ALREADY_EXISTS",
	permissionDeniedCode:   "PERMISSION_DENIED",
	unauthenticatedCode:    "UNAUTHENTICATED",
	resourceExhaustedCode:  "RESOURCE_EXHAUSTED",
	failedPreconditionCode: "FAILED_PRECONDITION",
	abortedCode:            "ABORTED",
	outOfRangeCode:         "OUT_OF_RANGE",
	unimplementedCode:      "UNIMPLEMENTED",
	internalCode:           "INTERNAL",
	unavailableCode:        "UNAVAILABLE",
	dataLossCode:           "DATA_LOSS",
}

// statusError is the type implementing the `error` interface returned by ToError().
//
// Its value is the integer `StatusCode.code`. It should match one of the value
// of `code` but it can be another unknown value.
type statusError int32

// value returns the integer code.
func (se statusError) value() int32 {
	return int32(se)
}

// Error returns the name of the code if known. Returns "ERROR(x)" with x the
// code integer value when no name is known.
func (se statusError) Error() string {
	if name, ok := codeName[code(se.value())]; ok {
		return name
	}
	return fmt.Sprintf("ERROR(%v)", se.value())
}

// Error values for errors returned by ToError().
//
// These values are wrapped with the message using %w, see
// https://blog.golang.org/go1.13-errors for details.
//
// Note that if the `StatusCode.code` is unknown then the wrapped error is not
// one of that list. The function ErrorCode() can retrieve the code in that
// case.
var (
	ErrCancelled          error = statusError(cancelledCode)
	ErrUnknown            error = statusError(unknownCode)
	ErrInvalidArgument    error = statusError(invalidArgumentCode)
	ErrDeadlineExceeded   error = statusError(deadlineExceededCode)
	ErrNotFound           error = statusError(notFoundCode)
	ErrAlreadyExists      error = statusError(alreadyExistsCode)
	ErrPermissionDenied   error = statusError(permissionDeniedCode)
	ErrUnauthenticated    error = statusError(unauthenticatedCode)
	ErrResourceExhausted  error = statusError(resourceExhaustedCode)
	ErrFailedPrecondition error = statusError(failedPreconditionCode)
	ErrAborted            error = statusError(abortedCode)
	ErrOutOfRange         error = statusError(outOfRangeCode)
	ErrUnimplemented      error = statusError(unimplementedCode)
	ErrInternal           error = statusError(internalCode)
	ErrUnavailable        error = statusError(unavailableCode)
	ErrDataLoss           error = statusError(dataLossCode)
)

// ErrorCode returns the (code, true) of the error returned by ToError(). It returns
// (0, false) if the input error does not wrap an error returned by ToError().
//
// See https://blog.golang.org/go1.13-errors for error wrapping.
func ErrorCode(err error) (int32, bool) {
	var statusErr statusError
	if !errors.As(err, &statusErr) {
		return 0, false
	}
	return statusErr.value(), true
}

// ToError returns the error corresponding to the input absl::Status; nil if OK.
//
// The error is built by wrapping one of the ErrXxx errors with the status
// message (see https://blog.golang.org/go1.13-errors). If the input status'
// code does not match one of the existing constant, ErrorCode() can be used to
// get the code number.
func ToError(status *spb.StatusProto) error {
	if status.GetCode() == okCode.value() {
		return nil
	}
	return fmt.Errorf("%w: %v", statusError(status.GetCode()), status.GetMessage())
}
