// Copyright 2010-2025 Google LLC
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package statusstreaming translates ortools/util StatusProto to Go errors.
//
// Errors generated by ToError() use error wrapping as described in
// https://blog.golang.org/go1.13-errors. The function errors.Is() can be used
// by with ErrXxx errors to test the type of error.
//
// The function ErrorCode() can be used to get the code of the error. It also
// tests if one of the wrapped error has been generated by ToError() even when
// the code does not match a known value defined by ErrXxx constants.
package statusstreaming

import (
	"errors"
	"fmt"

	spb "ortools/util/status_go_proto"
)

// Code are the C++ absl::Status::code() values.
type Code int32

// Value returns the underlying integer value.
func (c Code) Value() int32 {
	return int32(c)
}

// Canonical values of absl::Status::code().
var (
	OkCode                 = Code(0)
	CancelledCode          = Code(1)
	UnknownCode            = Code(2)
	InvalidArgumentCode    = Code(3)
	DeadlineExceededCode   = Code(4)
	NotFoundCode           = Code(5)
	AlreadyExistsCode      = Code(6)
	PermissionDeniedCode   = Code(7)
	UnauthenticatedCode    = Code(16)
	ResourceExhaustedCode  = Code(8)
	FailedPreconditionCode = Code(9)
	AbortedCode            = Code(10)
	OutOfRangeCode         = Code(11)
	UnimplementedCode      = Code(12)
	InternalCode           = Code(13)
	UnavailableCode        = Code(14)
	DataLossCode           = Code(15)
)

// codeName contains a name for each value of Code
var codeName = map[Code]string{
	OkCode:                 "OK",
	CancelledCode:          "CANCELLED",
	UnknownCode:            "UNKNOWN",
	InvalidArgumentCode:    "INVALID_ARGUMENT",
	DeadlineExceededCode:   "DEADLINE_EXCEEDED",
	NotFoundCode:           "NOT_FOUND",
	AlreadyExistsCode:      "ALREADY_EXISTS",
	PermissionDeniedCode:   "PERMISSION_DENIED",
	UnauthenticatedCode:    "UNAUTHENTICATED",
	ResourceExhaustedCode:  "RESOURCE_EXHAUSTED",
	FailedPreconditionCode: "FAILED_PRECONDITION",
	AbortedCode:            "ABORTED",
	OutOfRangeCode:         "OUT_OF_RANGE",
	UnimplementedCode:      "UNIMPLEMENTED",
	InternalCode:           "INTERNAL",
	UnavailableCode:        "UNAVAILABLE",
	DataLossCode:           "DATA_LOSS",
}

// statusError is the type implementing the `error` interface returned by ToError().
//
// Its value is the integer `StatusCode.code`. It should match one of the value
// of `Code` but it can be another unknown value.
type statusError int32

// value returns the integer code.
func (se statusError) value() int32 {
	return int32(se)
}

// Error returns the name of the code if known. Returns "ERROR(x)" with x the
// code integer value when no name is known.
func (se statusError) Error() string {
	if name, ok := codeName[Code(se.value())]; ok {
		return name
	}
	return fmt.Sprintf("ERROR(%v)", se.value())
}

// Error values for errors returned by ToError().
//
// These values are wrapped with the message using %w, see
// https://blog.golang.org/go1.13-errors for details.
//
// Note that if the `StatusCode.code` is unknown then the wrapped error is not
// one of that list. The function ErrorCode() can retrieve the code in that
// case.
var (
	ErrCancelled          error = statusError(CancelledCode)
	ErrUnknown            error = statusError(UnknownCode)
	ErrInvalidArgument    error = statusError(InvalidArgumentCode)
	ErrDeadlineExceeded   error = statusError(DeadlineExceededCode)
	ErrNotFound           error = statusError(NotFoundCode)
	ErrAlreadyExists      error = statusError(AlreadyExistsCode)
	ErrPermissionDenied   error = statusError(PermissionDeniedCode)
	ErrUnauthenticated    error = statusError(UnauthenticatedCode)
	ErrResourceExhausted  error = statusError(ResourceExhaustedCode)
	ErrFailedPrecondition error = statusError(FailedPreconditionCode)
	ErrAborted            error = statusError(AbortedCode)
	ErrOutOfRange         error = statusError(OutOfRangeCode)
	ErrUnimplemented      error = statusError(UnimplementedCode)
	ErrInternal           error = statusError(InternalCode)
	ErrUnavailable        error = statusError(UnavailableCode)
	ErrDataLoss           error = statusError(DataLossCode)
)

// ErrorCode returns the (code, true) of the error returned by ToError(). It returns
// (0, false) if the input error does not wrap an error returned by ToError().
//
// See https://blog.golang.org/go1.13-errors for error wrapping.
func ErrorCode(err error) (int32, bool) {
	var statusErr statusError
	if !errors.As(err, &statusErr) {
		return 0, false
	}
	return statusErr.value(), true
}

// ToError returns the error corresponding to the input absl::Status; nil if OK.
//
// The error is built by wrapping one of the ErrXxx errors with the status
// message (see https://blog.golang.org/go1.13-errors). If the input status'
// code does not match one of the existing constant, ErrorCode() can be used to
// get the code number.
func ToError(status *spb.StatusProto) error {
	if status.GetCode() == OkCode.Value() {
		return nil
	}
	return fmt.Errorf("%w: %v", statusError(status.GetCode()), status.GetMessage())
}
