# ref: https://github.com/actions/runner-images
name: amd64 Linux CMake Java

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environement directly.
jobs:
  native:
    name: amd64•Linux•CMake•Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Swig install
        run: |
          sudo apt install -y swig
          swig -version
      - name: Check java
        run: java -version
      - name: Check CMake
        run: cmake --version
      - name: Configure
        run: >
          cmake -S. -Bbuild
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_CXX_SAMPLES=OFF -DBUILD_CXX_EXAMPLES=OFF
          -DBUILD_JAVA=ON -DSKIP_GPG=ON
          -DCMAKE_INSTALL_PREFIX=install
      - name: Build
        run: >
          cmake --build build
          --config Release
          --target all
          -v -j2
      - name: Test
        run: >
          CTEST_OUTPUT_ON_FAILURE=1
          cmake --build build
          --config Release
          --target test
          -v
      - name: Install
        run: >
          cmake --build build
          --config Release
          --target install
          -v

  amd64_linux_cmake_java:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v4
