# ref: https://github.com/actions/runner-images
name: amd64 Windows CMake .Net

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environment directly.
jobs:
  native:
    strategy:
      matrix:
        cmake: [
          {name: "Ninja", generator: "Ninja", config: Release, build_target: all, test_target: test, install_target: install},
          #{name: "VS26", generator: "Visual Studio 18 2026", config: Release, build_target: ALL_BUILD, test_target: RUN_TESTS, install_target: INSTALL},
        ]
      fail-fast: false
    name: amd64•Windows•CMake(${{matrix.cmake.name}})•.Net
    runs-on: windows-latest
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/remote_cache
        with:
          credentials_json: '${{secrets.GCP_BUCKET_API_KEY}}'
          set_cmake_sccache_launcher: true
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 8.0.x
      - name: Check dotnet
        run: dotnet --info
      # Extract and inject MSVC environment variables
      - name: Set up MSVC x64
        if: ${{matrix.cmake.generator == 'Ninja'}}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Check CMake
        run: |
          cmake --version
          cmake -G || true
      - name: Configure
        run: >
          cmake -S. -Bbuild
          -G "${{matrix.cmake.generator}}"
          -DCMAKE_BUILD_TYPE=${{matrix.cmake.config}}
          -DCMAKE_CONFIGURATION_TYPES=${{matrix.cmake.config}}
          -DBUILD_CXX_SAMPLES=OFF -DBUILD_CXX_EXAMPLES=OFF
          -DBUILD_DOTNET=ON
      - id: num_cores
        uses: ./.github/actions/num_cores
      - name: Build
        run: >
          cmake --build build
          --config ${{matrix.cmake.config}}
          --target ${{matrix.cmake.build_target}}
          -j${{ steps.num_cores.outputs.cores }}
          -v
      - name: Test
        run: >
          cmake --build build
          --config ${{matrix.cmake.config}}
          --target ${{matrix.cmake.test_target}}
          -j${{ steps.num_cores.outputs.cores }}
          -v
      - name: Install
        run: >
          cmake --build build
          --config ${{matrix.cmake.config}}
          --target ${{matrix.cmake.install_target}}
          -v

  amd64_windows_cmake_dotnet:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v7
