# ref: https://github.com/actions/runner-images
name: amd64 Linux CMake Java

on:
  push:
    branches:
      - ci
      - main
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environment directly.
jobs:
  native:
    name: amd64•Linux•CMake•Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/remote_cache
        with:
          credentials_json: '${{secrets.GCP_BUCKET_API_KEY}}'
          set_cmake_sccache_launcher: true
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build swig
          swig -version
          echo "JAVA_HOME=$JAVA_HOME_21_X64" >> $GITHUB_ENV

      - name: Check CMake
        run: cmake --version
      - name: Configure
        run: >
          cmake -S. -Bbuild
          -G "Ninja"
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_CXX_SAMPLES=OFF -DBUILD_CXX_EXAMPLES=OFF
          -DBUILD_JAVA=ON -DSKIP_GPG=ON
          -DCMAKE_INSTALL_PREFIX=install
      - id: num_cores
        uses: ./.github/actions/num_cores
      - name: Build
        run: >
          cmake --build build
          --config Release
          --target all
          -j${{ steps.num_cores.outputs.cores }}
          -v
      - name: Test
        run: >
          CTEST_OUTPUT_ON_FAILURE=1
          cmake --build build
          --config Release
          --target test
          -j${{ steps.num_cores.outputs.cores }}
          -v
      - name: Install
        run: >
          cmake --build build
          --config Release
          --target install
          -v
  amd64_linux_cmake_java:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v6
