# ref: https://github.com/actions/runner-images
name: amd64 MacOS Bazel

on: [push, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

env:
  BAZEL_OUTPUT_ROOT: /private/tmp/bazel

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        python: [
          #{version: '3.10'},
          #{version: '3.11'},
          {version: '3.12'},
          #{version: '3.13'},
        ]
      fail-fast: false
    name: amd64•MacOS•Bazel•Python-${{matrix.python.version}}
    runs-on: macos-13 # last macos intel based runner
    steps:
      - uses: actions/checkout@v5
      - name: Set Java to OpenJDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check mvn
        run: mvn --version
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python.version}}
      - name: Check Python
        run: python --version
      - name: Check Bazel
        run: bazel version
      - name: Change Python in .bazelrc
        run: |
          sed -i '' -e 's/\(python_version=\)3.[0-9]*/\1${{matrix.python.version}}/g' .bazelrc
          cat .bazelrc
      - name: Change Python in MODULE.bazel
        run: |
          sed -i '' -e 's/\(DEFAULT_PYTHON =\) "3.[0-9]*"/\1 "${{matrix.python.version}}"/g' MODULE.bazel
          cat MODULE.bazel
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: ${{env.BAZEL_OUTPUT_ROOT}}
          key: amd64•MacOS•Bazel•Python-${{matrix.python.version}}
      - name: Build
        run: bazel --output_user_root=${{env.BAZEL_OUTPUT_ROOT}} build --config=ci //ortools/... //examples/...
      - name: Test
        run: bazel --output_user_root=${{env.BAZEL_OUTPUT_ROOT}} test --config=ci //ortools/... //examples/...

  amd64_macos_bazel:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v5
