name: amd64 MacOS Make .Net

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install brew Make
      run: |
        brew install make
        echo "/usr/local/opt/make/libexec/gnubin" >> $GITHUB_PATH
      # Install .NET SDKs
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Check dotnet
      run: dotnet --info
    - name: Swig install
      run: brew install swig
    - name: Check swig
      run: swig -version
    - name: Check make
      run: make --version
    - name: Check system
      run: make detect_port
    - name: Check .Net
      run: make detect_dotnet
    - name: Build C++ and .NET
      run: make dotnet JOBS=4
    - name: Test .Net
      run: make test_dotnet -j4
    - name: Create nuget packages
      run: make package_dotnet
