# ref: https://github.com/actions/runner-images
name: amd64 MacOS Bazel

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        python: [
          {version: '3.9'},
          {version: '3.10'},
          {version: '3.11'},
          {version: '3.12'},
        ]
      fail-fast: false
    name: MacOS • Bazel • Python-${{ matrix.python.version }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Java to OpenJDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check mvn
        run: mvn --version
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
      - name: Check Python
        run: python --version
      - name: Check Bazel
        run: bazel version
      - name: Change Python in WORKSPACE
        run: >
          sed
          -i ''
          -e 's/\(DEFAULT_PYTHON =\) "3.[0-9]*"/\1 "${{ matrix.python.version }}"/g'
          WORKSPACE
      - name: Build
        run: >
          bazel build
          -c opt
          --subcommands=pretty_print
          //ortools/... //examples/...
      - name: Test
        run: >
          bazel test
          -c opt
          --test_output=errors
          //ortools/... //examples/...
