name: Bazel MacOS

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

jobs:
  bazel:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Bazel
        run: |
          brew update
          #brew install bazel
          bazel --version
      - name: Build
        run: bazel build -c opt --cxxopt=-std=c++20 //ortools/... //examples/...
      - name: Test
        run: bazel test -c opt --cxxopt=-std=c++20 --test_output=errors //ortools/... //examples/...
