name: CMake GLPK ON

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  linux_cpp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check cmake
      run: cmake --version
    - name: Configure
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_DEPS=ON
        -DBUILD_CXX=ON -DUSE_GLPK=ON -DUSE_SCIP=OFF -DUSE_COINOR=OFF
    - name: Build
      run: cmake --build build --config Release --target all -v
    - name: Test
      run: CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --config Release --target test -v
    - name: Install
      run: cmake --build build --config Release --target install -v -- DESTDIR=install
