name: CMake MacOS .Net

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  cmake_make:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check cmake
      run: cmake --version
    - name: Swig install
      run: brew install swig
    - name: Check swig
      run: swig -version
    - name: Check dotnet
      run: dotnet --info
    - name: Configure
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_DOTNET=ON -DBUILD_CXX_SAMPLES=OFF -DBUILD_CXX_EXAMPLES=OFF
    - name: Build
      run: cmake --build build --target all -v
    - name: Test
      run: CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target test -v
    - name: Install
      run: cmake --build build --target install -v -- DESTDIR=install
