# ref: https://toolchains.bootlin.com/
name: powerpc Toolchain

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  powerpc:
    strategy:
      matrix:
        targets: [ppc64, ppc64le]
      fail-fast: false
    name: Linux • Toolchain ${{ matrix.targets }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build env stage
      run: make --directory=cmake toolchain_${{ matrix.targets }}_env
    - name: Build devel stage
      run: make --directory=cmake toolchain_${{ matrix.targets }}_devel
    - name: Build build stage
      run: make --directory=cmake toolchain_${{ matrix.targets }}_build
    - name: Build Test stage
      run: make --directory=cmake toolchain_${{ matrix.targets }}_test
