# ref: https://github.com/actions/runner-images
name: Release

on:
  push:
    branches:
      - rc
      - mizux/rc
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref_name}}
  cancel-in-progress: true

env:
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '21'
  # Disable auth (and caching) when running from a fork.
  # By default, secrets are not passed to workflows triggered from forks, including Dependabot.
  USE_GOOGLE_CLOUD_STORAGE: ${{! (github.event.pull_request.head.repo.fork || false)}}
  ORTOOLS_TOKEN: ${{secrets.ORTOOLS_TOKEN}}
  OR_TOOLS_PATCH: 0
jobs:
###############################################################################
# Build Native Delivery
  native_delivery:
    strategy:
      fail-fast: false
      matrix:
        platform: [
          { runner: "ubuntu-22.04",     arch: "amd64", os: "linux" },
          { runner: "ubuntu-22.04-arm", arch: "arm64", os: "linux" },
          { runner: "macos-15-intel",   arch: "amd64", os: "macos" },
          { runner: "macos-latest",     arch: "arm64", os: "macos" },
          { runner: "windows-latest",   arch: "amd64", os: "windows" }
        ]
        target: [
          { name: "cpp",       lang: "cpp",    version: "20" },
          { name: "dotnet",    lang: "dotnet", version: "8.0.x" },
          { name: "java",      lang: "java",   version: "21" },
        ]
    name: Build(${{matrix.platform.arch}}•${{matrix.platform.os}}•${{matrix.target.name}})
    runs-on: ${{matrix.platform.runner}}
    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/actions/remote_cache
      with:
        credentials_json: '${{secrets.GCP_BUCKET_API_KEY}}'
        set_cmake_sccache_launcher: true
    - uses: ./.github/actions/setup
      with:
        arch: ${{matrix.platform.arch}}
        os: ${{matrix.platform.os}}
        lang: ${{matrix.target.lang}}
        version: ${{matrix.target.version}}
    - name: Build Linux ${{matrix.target.name}} Delivery
      if: ${{matrix.platform.os == 'linux'}}
      run: ./tools/release/build_delivery_linux.sh ${{matrix.target.lang}} ${{matrix.target.version}}
    - name: Build MacOS ${{matrix.target.name}} Delivery
      if: ${{matrix.platform.os == 'macos'}}
      run: ./tools/release/build_delivery_macos.sh ${{matrix.target.lang}} ${{matrix.target.version}}
    - name: Build Windows ${{matrix.target.name}} Delivery
      if: ${{matrix.platform.os == 'windows'}}
      run: ./tools/release/build_delivery_windows.cmd ${{matrix.target.lang}} ${{matrix.target.version}}
    - name: Check export dir
      run: ls -R export
    - name: Upload Tarball Artifact
      uses: actions/upload-artifact@v7
      with:
        name: ortools-${{matrix.platform.arch}}-${{matrix.platform.os}}-${{matrix.target.name}}
        path: |
          build.log
          export/*.tar.gz
          export/*.zip
          export/*.nupkg
          export/*.jar
          export/*.whl
        if-no-files-found: error
        retention-days: 1

###############################################################################
# Test Delivery
  test_native_delivery:
    strategy:
      fail-fast: false
      matrix:
        platform: [
          { runner: "ubuntu-22.04",     arch: "amd64", os: "linux" },
          { runner: "ubuntu-22.04-arm", arch: "arm64", os: "linux" },
          { runner: "macos-15-intel",   arch: "amd64", os: "macos" },
          { runner: "macos-latest",     arch: "arm64", os: "macos" },
          { runner: "windows-latest",   arch: "amd64", os: "windows" }
        ]
        target: [
          { name: "cpp",       lang: "cpp",    version: "20" },
          { name: "dotnet",    lang: "dotnet", version: "8.0.x" },
          { name: "java",      lang: "java",   version: "21" },
        ]
    name: Test(${{matrix.platform.arch}}•${{matrix.platform.os}}•${{matrix.target.name}})
    runs-on: ${{matrix.platform.runner}}
    needs: native_delivery
    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/actions/setup
      with:
        arch: ${{matrix.platform.arch}}
        os: ${{matrix.platform.os}}
        lang: ${{matrix.target.lang}}
        version: ${{matrix.target.version}}
    - name: Download Tarball Artifact
      uses: actions/download-artifact@v8
      with:
        name: ortools-${{matrix.platform.arch}}-${{matrix.platform.os}}-${{matrix.target.name}}
        path: .
    - name: Check export dir
      run: ls -R export
    - name: Test Linux ${{matrix.target.name}} Delivery
      if: ${{matrix.platform.os == 'linux'}}
      run: ./tools/release/test_delivery_linux.sh ${{matrix.target.lang}} ${{matrix.target.version}}
    - name: Test MacOS ${{matrix.target.name}} Delivery
      if: ${{matrix.platform.os == 'macos'}}
      run: ./tools/release/test_delivery_macos.sh ${{matrix.target.lang}} ${{matrix.target.version}}
    - name: Test Windows ${{matrix.target.name}} Delivery
      if: ${{matrix.platform.os == 'windows'}}
      run: ./tools/release/test_delivery_windows.cmd ${{matrix.target.lang}} ${{matrix.target.version}}

###############################################################################
# Build Meta Delivery
  meta_delivery:
    strategy:
      fail-fast: false
      matrix:
        target: [
          { name: "dotnet", lang: "dotnet", version: "8.0.x" },
          { name: "java",   lang: "java",   version: "21" }
        ]
    name: Build(meta•${{matrix.target.name}})
    runs-on: ubuntu-22.04
    needs: native_delivery
    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/actions/remote_cache
      with:
        credentials_json: '${{secrets.GCP_BUCKET_API_KEY}}'
        set_cmake_sccache_launcher: true
    - uses: ./.github/actions/setup
      with:
        arch: amd64
        os: linux
        lang: ${{matrix.target.lang}}
        version: ${{matrix.target.version}}
    - name: Download Native Artifacts
      uses: actions/download-artifact@v8
      with:
        pattern: "ortools-*-*-${{matrix.target.name}}"
        merge-multiple: true
        path: .
    - name: Check Export dir
      run: ls -R export
    - name: Build ${{matrix.target.name}} Meta Delivery
      run: ./tools/release/build_delivery_meta.sh ${{matrix.target.lang}}
    - name: Check export_meta
      run: ls -R export_meta
    - name: Upload Meta Artifact
      uses: actions/upload-artifact@v7
      with:
        name: ortools-meta-${{matrix.target.name}}
        path: |
          build.log
          export_meta/*.nupkg
          export_meta/*.snupkg
          export_meta/*.jar
          export_meta/*.asc
        if-no-files-found: error
        retention-days: 1

###############################################################################
# Test Meta Delivery
  test_meta:
    strategy:
      fail-fast: false
      matrix:
        platform: [
          { runner: "ubuntu-22.04",     arch: "amd64", os: "linux" },
          { runner: "ubuntu-22.04-arm", arch: "arm64", os: "linux" },
          { runner: "macos-15-intel",   arch: "amd64", os: "macos" },
          { runner: "macos-latest",     arch: "arm64", os: "macos" },
          { runner: "windows-latest",   arch: "amd64", os: "windows" }
        ]
        target: [
          { name: "dotnet", lang: "dotnet", version: "8.0.x" },
          { name: "java",   lang: "java",   version: "21" }
        ]
    name: Test(${{matrix.platform.arch}}•${{matrix.platform.os}}•meta•${{matrix.target.name}})
    runs-on: ${{matrix.platform.runner}}
    needs: meta_delivery
    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/actions/setup
      with:
        arch: ${{matrix.platform.arch}}
        os: ${{matrix.platform.os}}
        lang: ${{matrix.target.lang}}
        version: ${{matrix.target.version}}
    - name: Download Native Artifacts
      uses: actions/download-artifact@v8
      with:
        pattern: "ortools-*-*-${{matrix.target.name}}"
        merge-multiple: true
        path: .
    - name: Download Meta Artifact
      uses: actions/download-artifact@v8
      with:
        name: ortools-meta-${{matrix.target.name}}
        path: .
    - name: Copy Meta Artifact to export
      shell: bash
      run: cp -f export_meta/* export/
    - name: Check Export dir
      run: ls -R export
    - name: Test Linux ${{matrix.target.name}} Meta Delivery
      if: ${{matrix.platform.os == 'linux'}}
      run: ./tools/release/test_delivery_linux.sh ${{matrix.target.lang}}
    - name: Test MacOS ${{matrix.target.name}} Meta Delivery
      if: ${{matrix.platform.os == 'macos'}}
      run: ./tools/release/test_delivery_macos.sh ${{matrix.target.lang}}
    - name: Test Windows ${{matrix.target.name}} Meta Delivery
      if: ${{matrix.platform.os == 'windows'}}
      run: ./tools/release/test_delivery_windows.cmd ${{matrix.target.lang}}

###############################################################################
# DOCKER ARCHIVES
  distro_archives:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64]
        os: [
          almalinux-10,
          alpine-edge,
          archlinux,
          debian-sid,
          debian-13,
          debian-12,
          fedora-44,
          fedora-43,
          opensuse-leap,
          rockylinux-10,
          ubuntu-26.04,
          ubuntu-24.04,
          ubuntu-22.04,
        ]
        lang: [cpp, dotnet, java, python]
        exclude:
          # debian-12 only provide openjdk 17
          - os: debian-12
            lang: java
    name: Distro(${{matrix.arch}}•${{matrix.os}}•${{matrix.lang}})
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: retrieve or-tools.snk
      run: >
        openssl aes-256-cbc -iter 42 -pass pass:"$ORTOOLS_TOKEN"
        -in "tools/release/or-tools.snk.enc"
        -out "tools/docker/or-tools.snk" -d
    - name: Build ${{matrix.lang}}
      run: make --directory=tools/docker ${{matrix.arch}}_${{matrix.os}}_${{matrix.lang}}_build
    - name: Export ${{matrix.lang}}
      run: make --directory=tools/docker ${{matrix.arch}}_${{matrix.os}}_${{matrix.lang}}_export
    - name: Test ${{matrix.lang}} export
      run: make --directory=tools/docker ${{matrix.arch}}_${{matrix.os}}_${{matrix.lang}}_test
    - name: Check Export dir
      run: ls -R tools/docker/export
    - name: Upload Tarball Artifact
      uses: actions/upload-artifact@v7
      with:
        path: |
          tools/docker/export/archives/*.tar.gz
        archive: false
        if-no-files-found: error
        retention-days: 1

###############################################################################
# Pythons
## Python Manylinux
  python_manylinux:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64] # arm64
        distro: [manylinux, musllinux]
        python: [
          310,
          311,
          312,
          313,
          314
        ]
    name: Python(${{matrix.arch}}•${{matrix.distro}}•cp${{matrix.python}})
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Build Whl
      run: >
        make --directory=tools/docker
        python_${{matrix.arch}}_${{matrix.distro}}_cp${{matrix.python}}_build
    - name: Export Whl
      run: >
        make --directory=tools/docker
        python_${{matrix.arch}}_${{matrix.distro}}_cp${{matrix.python}}_export
    - name: Check Export dir
      run: ls -R tools/docker/export
    - name: Upload Tarball Artifact
      uses: actions/upload-artifact@v7
      with:
        path: |
          tools/docker/export/python/ortools-*${{matrix.distro}}*.whl
        archive: false
        if-no-files-found: error
        retention-days: 1

##  Python MacOS & Windows
  python_mac_win:
    strategy:
      fail-fast: false
      matrix:
        platform: [
          { runner: "macos-15-intel",   arch: "amd64", os: "macos" },
          { runner: "macos-latest",     arch: "arm64", os: "macos" },
          { runner: "windows-latest",   arch: "amd64", os: "windows" }
        ]
        target: [
          { name: "python310", lang: "python", version: "10" },
          { name: "python311", lang: "python", version: "11" },
          { name: "python312", lang: "python", version: "12" },
          { name: "python313", lang: "python", version: "13" },
          { name: "python314", lang: "python", version: "14" }
        ]
        exclude:
          # setup/python do not provide python 3.10 alias
          - platform: {os: macos, arch: amd64 }
            target: {lang: python, version: 10 }
    name: Build(${{matrix.platform.arch}}•${{matrix.platform.os}}•${{matrix.target.name}})
    runs-on: ${{matrix.platform.runner}}
    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/actions/remote_cache
      with:
        credentials_json: '${{secrets.GCP_BUCKET_API_KEY}}'
        set_cmake_sccache_launcher: true
    - uses: ./.github/actions/setup
      with:
        arch: ${{matrix.platform.arch}}
        os: ${{matrix.platform.os}}
        lang: ${{matrix.target.lang}}
        version: ${{matrix.target.version}}
        build_deps: true
    - name: Build Linux ${{matrix.target.name}} Delivery
      if: ${{matrix.platform.os == 'linux'}}
      run: ./tools/release/build_delivery_linux.sh ${{matrix.target.lang}} ${{matrix.target.version}}
    - name: Build MacOS ${{matrix.target.name}} Delivery
      if: ${{matrix.platform.os == 'macos'}}
      run: ./tools/release/build_delivery_macos.sh ${{matrix.target.lang}} ${{matrix.target.version}}
    - name: Build Windows ${{matrix.target.name}} Delivery
      if: ${{matrix.platform.os == 'windows'}}
      run: ./tools/release/build_delivery_windows.cmd ${{matrix.target.lang}} ${{matrix.target.version}}
    - name: Check export dir
      run: ls -R export
    - name: Upload Tarball Artifact
      uses: actions/upload-artifact@v7
      with:
        path: |
          export/*.whl
        archive: false
        if-no-files-found: error
        retention-days: 1

## Test Python MacOS & Windows
  test_python_mac_win:
    strategy:
      fail-fast: false
      matrix:
        platform: [
          { runner: "macos-15-intel",   arch: "amd64", os: "macos",   py_os: "macosx", py_arch: "x86_64" },
          { runner: "macos-latest",     arch: "arm64", os: "macos",   py_os: "macosx", py_arch: "arm64" },
          { runner: "windows-latest",   arch: "amd64", os: "windows", py_os: "win",    py_arch: "amd64" }
        ]
        target: [
          { name: "python310", lang: "python", version: "10" },
          { name: "python311", lang: "python", version: "11" },
          { name: "python312", lang: "python", version: "12" },
          { name: "python313", lang: "python", version: "13" },
          { name: "python314", lang: "python", version: "14" }
        ]
        exclude:
          # setup/python do not provide python 3.10 alias
          - platform: {os: macos, arch: amd64 }
            target: {lang: python, version: 10 }
    name: Test(${{matrix.platform.arch}}•${{matrix.platform.os}}•${{matrix.target.name}})
    runs-on: ${{matrix.platform.runner}}
    needs: python_mac_win
    steps:
    - uses: actions/checkout@v7
    - uses: ./.github/actions/setup
      with:
        arch: ${{matrix.platform.arch}}
        os: ${{matrix.platform.os}}
        lang: ${{matrix.target.lang}}
        version: ${{matrix.target.version}}
    - name: Download Tarball Artifact
      uses: actions/download-artifact@v8
      with:
        pattern: "ortools-*-cp3${{matrix.target.version}}-${{matrix.platform.py_os}}_*${{matrix.platform.py_arch}}.whl"
        path: export/
    - name: Check Export dir
      run: ls -R export
    - name: Test Linux ${{matrix.target.name}} Delivery
      if: ${{matrix.platform.os == 'linux'}}
      run: ./tools/release/test_delivery_linux.sh ${{matrix.target.lang}} ${{matrix.target.version}}
    - name: Test MacOS ${{matrix.target.name}} Delivery
      if: ${{matrix.platform.os == 'macos'}}
      run: ./tools/release/test_delivery_macos.sh ${{matrix.target.lang}} ${{matrix.target.version}}
    - name: Test Windows ${{matrix.target.name}} Delivery
      if: ${{matrix.platform.os == 'windows'}}
      run: ./tools/release/test_delivery_windows.cmd ${{matrix.target.lang}} ${{matrix.target.version}}
