# ref: https://github.com/actions/runner-images
name: Windows knitro tests

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    env :
      KNITRODIR: ${{ github.workspace }}\knitro_distrib\knitro-14.0.0-Win64
      ARTELYS_LICENSE: ${{ github.workspace }}\knitro_distrib
      OR_ROOT: ${{ github.workspace }}
    strategy:
      matrix:
        cmake: [
          {generator: "Visual Studio 17 2022", config: Release, build_target: ALL_BUILD, test_target: RUN_TESTS, install_target: INSTALL},
        ]
      fail-fast: false
    name: Windows • Knitro Test • C++
    runs-on: windows-latest
    steps:
      - name: Checkout or-tools
        uses: actions/checkout@v4
      - name: Checkout Knitro Windows
        uses: actions/checkout@v4
        with:
          repository: loicli/knitro1400-Win64
          path: knitro_distrib
          token: ${{ secrets.KNITRO_DISTRIB }}
      - name: Unzip
        run: |
          7z x "${{ env.KNITRODIR }}/knitroampl/knitroampl.zip" -o"${{ env.KNITRODIR }}/knitroampl"
          7z x "${{ env.KNITRODIR }}/knitromatlab/knitromatlab_mex.zip" -o"${{ env.KNITRODIR }}/knitromatlab"
          7z x "${{ env.KNITRODIR }}/lib/knitro.zip" -o"${{ env.KNITRODIR }}/lib"
          rm ${{ env.KNITRODIR }}/knitroampl/knitroampl.zip
          rm ${{ env.KNITRODIR }}/knitromatlab/knitromatlab_mex.zip
          rm ${{ env.KNITRODIR }}/lib/knitro.zip
      - name: Copy license
        run: |
          echo "${{ secrets.KNITRO_DISTRIB_LICENSE }}" >> ${{ env.ARTELYS_LICENSE }}/artelys_lic_cicd.txt
      - name: Grant access to knitro distrib
        run: |
          icacls ${{ env.KNITRODIR }} /grant Everyone:RX /t
      - name: Check cmake
        run: |
          cmake --version
          cmake -G || true
      - name: Configure
        run: >
          cmake -S. -Bbuild
          -G "${{ matrix.cmake.generator }}"
          -DCMAKE_BUILD_TYPE=${{ matrix.cmake.config }}
          -DBUILD_DEPS=ON
          -DUSE_KNITRO=ON
          -DBUILD_TESTING=ON
      - name: Build
        run: >
          cmake --build build
          --config ${{ matrix.cmake.config }}
          --target ${{ matrix.cmake.build_target }}
          -v -j2
      - name: CHeck Build dir
        run: |
          ls -l build
      - name: Run Knitro Test
        run: >
          ./build/RELEASE/bin/test_knitro_interface
